-- Pawrexio legacy content migration. Safe to re-run.
begin;

update public.training_programs set title='Kitten Training', updated_at=now()
where slug='kitten-training' and category='Cat Training';

insert into public.blog_posts
 (title,slug,excerpt,content,category,published_at,featured_image_url,status,robots_index)
values
 ('Puppy Training in Gurgaon: Build a Happy & Well-Behaved Companion','puppy-training-happy-well-behaved-companion','Start early with professional puppy training, positive routines, socialisation and practical home guidance.','<p>Bringing home a puppy is exciting, but the first months shape behaviour for life. Early training builds communication and confidence.</p><h2>Why Early Puppy Training Is Important</h2><p>A planned routine prevents confusing habits and supports safe socialisation.</p><ul><li>Good habits from an early age</li><li>Fewer biting, jumping and toilet problems</li><li>A stronger family bond</li></ul><h2>Professional Puppy Training Center</h2><p>Pawrexio uses positive reinforcement and age-appropriate exercises.</p><h2>What Your Puppy Learns</h2><ul><li>Name response, sit, stay, come and leave it</li><li>Toilet, feeding and sleep routines</li><li>Bite inhibition, leash foundations and calm handling</li></ul><h2>Home & Center Training Options</h2><p>Home sessions address real routines while structured environments build focus.</p><h2>Why Choose Pawrexio?</h2><p>Experienced trainers combine humane methods with clear pet-parent coaching.</p><h2>Start Puppy Training Today</h2><p>Share your puppy''s age, breed, location and current challenges.</p>','Puppy Training','2026-08-18T09:00:00Z','/assets/real/puppy-focus.webp','published',true),
 ('Basic to Advanced Dog Training: Build Discipline From Day One','basic-to-advanced-dog-training','Compare progressive dog-training levels in Faridabad, Gurgaon and Delhi.','<p>Good behaviour develops step by step. Basic training creates communication; advanced training adds reliability.</p><h2>Basic Dog Training in Faridabad</h2><p>Essential cues, leash manners, socialisation and calm home behaviour.</p><h3>Who Is It Ideal For?</h3><p>Puppies, first-time pet parents and dogs needing clear boundaries.</p><h2>Basic Dog Training in Gurgaon</h2><p>Home and neighbourhood practice applies cues around doors, visitors, traffic and walks.</p><h2>Advanced Dog Training in Gurgaon</h2><p>Longer stays, stronger recall and impulse control.</p><h2>Advanced Dog Training in Delhi</h2><p>Distance, duration and distraction increase gradually.</p><h2>Advanced Dog Training in Faridabad</h2><p>Public manners and complex cues follow assessment.</p><h2>Final Thoughts</h2><p>The best package is the level your dog is ready for now.</p>','Dog Training','2026-08-10T09:00:00Z','/assets/real/obedience.webp','published',true),
 ('Dog Training in Mumbai: Professional & Trusted Pet Training Services','dog-training-in-mumbai-professional-trusted-services','Professional puppy, obedience, behaviour, home and leash-training support in Mumbai.','<p>Mumbai dogs navigate lifts, traffic, noise and stimulating walks. Training prepares them for real city life.</p><h2>Professional Dog Training in Mumbai</h2><p>Plans consider age, breed, health, temperament and history.</p><h2>Puppy Training in Mumbai</h2><p>Programs cover toilet routines, socialisation and first cues.</p><h2>Basic & Advanced Obedience Training</h2><p>Foundations progress to duration, distraction and recall.</p><h2>Behaviour Training</h2><p>Assessment-led support is available for barking, fear and reactivity.</p><h2>Leash Training & Walking Manners</h2><p>Dogs learn check-ins and loose-leash movement.</p><h2>Home Dog Training in Mumbai</h2><p>Home sessions address the environment where habits occur.</p><h2>Why Choose Pawrexio?</h2><ul><li>Experienced trainers</li><li>Positive personalised methods</li><li>Pet-parent coaching</li></ul>','Dog Training','2026-08-02T09:00:00Z','/assets/real/outdoor-focus.webp','published',true),
 ('Pet Training for Happy, Obedient & Well-Behaved Pets','pet-training-happy-obedient-well-behaved-pets','Personalised training for puppy foundations, obedience, behaviour and home routines.','<p>Pet training improves daily life by giving animals clear ways to succeed.</p><h2>Why Pet Training Is Important</h2><p>Training supports safety, confidence and predictable routines.</p><h2>Pet Training Services in Gurgaon</h2><h3>Puppy Training</h3><p>Toilet routines, bite inhibition and early cues.</p><h3>Basic Obedience Training</h3><p>Sit, stay, come and household manners.</p><h3>Behaviour Training</h3><p>Support for barking, fear, anxiety and unwanted habits.</p><h3>Home Pet Training</h3><p>Coaching where routines occur.</p><h3>Advanced Training</h3><p>Recall, distance and distraction control.</p><h2>Positive & Humane Training Methods</h2><p>Pawrexio uses rewards and clear communication.</p><h2>Training for Different Breeds & Temperaments</h2><p>Every plan begins with the individual pet.</p><h2>Real Training, Lasting Results</h2><p>Consistent practice turns lessons into habits.</p>','Pet Training','2026-07-25T09:00:00Z','/assets/real/training-session.webp','published',true),
 ('Leash Training for Dogs: A Practical Guide','leash-training-practical-guide','A step-by-step guide to loose-leash walking, common mistakes and calmer walks.','<p>Leash training makes walks safer and improves communication.</p><h2>Why Leash Training Is Important</h2><p>Training rewards attention, proximity and a loose leash.</p><h2>When to Start Leash Training</h2><p>Begin gentle familiarisation in puppyhood; adult dogs can learn too.</p><h2>Step-by-Step Leash Training Process</h2><ol><li>Choose comfortable equipment.</li><li>Build positive association.</li><li>Reward check-ins.</li><li>Practise quietly.</li><li>Progress gradually.</li></ol><h2>Common Leash Training Mistakes</h2><ul><li>Letting pulling reach every destination</li><li>Starting around too many distractions</li><li>Using inconsistent rules</li></ul><h2>Tips for Better Results</h2><p>Keep sessions short and allow appropriate sniffing.</p><h2>Benefits of Professional Leash Training</h2><p>A trainer can assess fear, excitement and handling.</p><h2>Conclusion</h2><p>Patient practice makes walks more enjoyable.</p>','Walking Skills','2026-07-16T09:00:00Z','/assets/real/walking.webp','published',true),
 ('Puppy Obedience Classes: Build the Perfect Foundation for Your Dog','puppy-obedience-classes-perfect-foundation','Early classes build communication, confidence, routines and essential life skills.','<p>Puppy obedience classes create a clear foundation and teach pet parents how to guide behaviour.</p><h2>Why Puppy Obedience Training Is Important</h2><p>Early lessons prevent confusing habits and support safe socialisation.</p><h2>Essential Puppy Training Techniques</h2><ul><li>Name response and attention</li><li>Sit, stay and recall</li><li>Toilet, sleep and feeding routines</li><li>Bite inhibition and leash introduction</li></ul><h2>Positive Reinforcement Training</h2><p>Food, play and praise make good choices worth repeating.</p><h2>Choosing the Right Puppy Obedience Class</h2><p>Choose humane methods and clear owner coaching.</p><h2>Advantages of Professional Puppy Training</h2><p>A trainer adjusts the plan to the puppy.</p><h2>Conclusion</h2><p>Consistency turns class exercises into lifelong skills.</p>','Puppy Training','2026-07-10T09:00:00Z','/assets/real/puppy-sit.webp','published',true),
 ('Dog Behaviour Training for Lasting Results','dog-behaviour-training-lasting-results','Understand the source of unwanted behaviour and create lasting change.','<p>Behaviour training looks beyond the visible problem because barking, fear and aggression can have different causes.</p><h2>Understanding the Source of Behaviour</h2><p>Assessment considers triggers, body language, health and history.</p><h2>Specialised Behaviour Training Techniques</h2><p>Management prevents rehearsal while rewards teach safer alternatives.</p><h2>Considering Breed & Environment</h2><p>Breed tendencies, personal history and environment all matter.</p><h2>Consistency Creates Lasting Change</h2><p>Every family member should use the same cues and rewards.</p><h2>Advanced Behaviour Training</h2><p>Duration, distance and distraction increase gradually.</p><h2>Benefits of Professional Behaviour Training</h2><ul><li>Structured assessment</li><li>Personalised management</li><li>Owner guidance</li></ul><h2>Conclusion</h2><p>Understanding why behaviour happens makes safer alternatives possible.</p>','Behaviour','2026-07-03T09:00:00Z','/assets/real/obedience.webp','published',true)
on conflict (slug) do update set title=excluded.title,excerpt=excluded.excerpt,content=excluded.content,
 category=excluded.category,published_at=excluded.published_at,featured_image_url=excluded.featured_image_url,
 status=excluded.status,robots_index=excluded.robots_index,updated_at=now();

insert into public.testimonials (customer_name,location,content,rating,verified,active,sort_order)
select 'Mariyanus Beck','Gurgaon','They trained my dog exceptionally well. The team was polite and professional, and my experience with them was really great.',5,true,true,5
where not exists (select 1 from public.testimonials where customer_name='Mariyanus Beck');

insert into public.testimonials (customer_name,location,content,rating,verified,active,sort_order)
select 'Rubina Ekka','Noida','Excellent dog training service. The trainers were professional, patient and genuinely cared about my dog''s progress.',5,true,true,6
where not exists (select 1 from public.testimonials where customer_name='Rubina Ekka');

commit;
