-- PAWREXIO production schema. Run in a new Supabase project using the SQL editor.
create extension if not exists pgcrypto;
create type public.admin_role as enum ('admin','editor');
create type public.content_status as enum ('draft','published','archived');
create type public.enquiry_status as enum ('new','contacted','follow_up','qualified','booked','completed','lost');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, role admin_role not null default 'editor', avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.services (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, kicker text, short_description text not null, description text not null, image_url text, duration text, price_from numeric(10,2), suitable_for text, benefits jsonb not null default '[]', status content_status not null default 'draft', sort_order int not null default 0, seo_title text, seo_description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.training_programs (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, level text, duration text, summary text not null, description text, image_url text, inclusions jsonb not null default '[]', price_from numeric(10,2), status content_status not null default 'draft', sort_order int not null default 0, seo_title text, seo_description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.locations (id uuid primary key default gen_random_uuid(), city text not null, state text not null, slug text unique not null, intro text not null, content text, image_url text, active boolean not null default false, seo_title text, seo_description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.blog_categories (id uuid primary key default gen_random_uuid(), name text unique not null, slug text unique not null, created_at timestamptz not null default now());
create table public.blog_posts (id uuid primary key default gen_random_uuid(), author_id uuid references public.profiles(id), category_id uuid references public.blog_categories(id) on delete set null, title text not null, slug text unique not null, excerpt text not null, content text not null, featured_image_url text, tags text[] not null default '{}', status content_status not null default 'draft', published_at timestamptz, seo_title text, seo_description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.gallery (id uuid primary key default gen_random_uuid(), image_url text not null, title text not null, caption text, category text, location_id uuid references public.locations(id) on delete set null, program_id uuid references public.training_programs(id) on delete set null, active boolean not null default true, sort_order int not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.testimonials (id uuid primary key default gen_random_uuid(), customer_name text not null, pet_name text, location text, rating smallint check(rating between 1 and 5), content text not null, image_url text, verified boolean not null default false, active boolean not null default false, sort_order int not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.faqs (id uuid primary key default gen_random_uuid(), question text not null, answer text not null, page_context text not null default 'general', active boolean not null default true, sort_order int not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.enquiries (id uuid primary key default gen_random_uuid(), full_name text not null, phone text not null, email text, city text not null, pet_type text not null, pet_name text, breed text, pet_age text, service_slug text, behaviour_concern text not null, preferred_date date, preferred_time text, message text, status enquiry_status not null default 'new', internal_notes text, follow_up_at timestamptz, assigned_to uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.site_settings (id text primary key default 'default', public_email text, phone text, whatsapp_number text, address text, social_links jsonb not null default '{}', footer_text text, updated_at timestamptz not null default now());

create index services_status_sort_idx on public.services(status,sort_order); create index programs_status_sort_idx on public.training_programs(status,sort_order); create index locations_active_idx on public.locations(active); create index posts_status_published_idx on public.blog_posts(status,published_at desc); create index enquiries_status_created_idx on public.enquiries(status,created_at desc); create index gallery_active_sort_idx on public.gallery(active,sort_order);

alter table public.profiles enable row level security; alter table public.services enable row level security; alter table public.training_programs enable row level security; alter table public.locations enable row level security; alter table public.blog_categories enable row level security; alter table public.blog_posts enable row level security; alter table public.gallery enable row level security; alter table public.testimonials enable row level security; alter table public.faqs enable row level security; alter table public.enquiries enable row level security; alter table public.site_settings enable row level security;
create function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and role in ('admin','editor')) $$;
create policy "published services public" on services for select using(status='published'); create policy "staff services" on services for all using(is_staff()) with check(is_staff());
create policy "published programs public" on training_programs for select using(status='published'); create policy "staff programs" on training_programs for all using(is_staff()) with check(is_staff());
create policy "active locations public" on locations for select using(active); create policy "staff locations" on locations for all using(is_staff()) with check(is_staff());
create policy "categories public" on blog_categories for select using(true); create policy "staff categories" on blog_categories for all using(is_staff()) with check(is_staff());
create policy "published posts public" on blog_posts for select using(status='published' and published_at<=now()); create policy "staff posts" on blog_posts for all using(is_staff()) with check(is_staff());
create policy "active gallery public" on gallery for select using(active); create policy "staff gallery" on gallery for all using(is_staff()) with check(is_staff());
create policy "verified testimonials public" on testimonials for select using(active and verified); create policy "staff testimonials" on testimonials for all using(is_staff()) with check(is_staff());
create policy "active faqs public" on faqs for select using(active); create policy "staff faqs" on faqs for all using(is_staff()) with check(is_staff());
create policy "staff enquiries" on enquiries for all using(is_staff()) with check(is_staff()); create policy "staff settings" on site_settings for all using(is_staff()) with check(is_staff()); create policy "public settings" on site_settings for select using(true); create policy "own profile" on profiles for select using(id=auth.uid() or is_staff());

insert into public.blog_categories(name,slug) values ('Puppy Training','puppy-training'),('Walking Skills','walking-skills'),('Cat Care','cat-care') on conflict do nothing;
insert into public.site_settings(id,public_email,footer_text) values ('default','hello@pawrexio.com','TRAIN • TRUST • TRANSFORM') on conflict do nothing;

-- Storage: create a public bucket named "media" in the dashboard, with 8 MB upload limit and image MIME allow-list.
create policy "public read media" on storage.objects for select using(bucket_id='media');
create policy "staff upload media" on storage.objects for insert to authenticated with check(bucket_id='media' and public.is_staff());
create policy "staff update media" on storage.objects for update to authenticated using(bucket_id='media' and public.is_staff());
create policy "admins delete media" on storage.objects for delete to authenticated using(bucket_id='media' and exists(select 1 from public.profiles where id=auth.uid() and role='admin'));
