import { BarChart3, Bell, BookOpen, ChevronDown, FileText, GalleryHorizontal, HelpCircle, Home, Inbox, LayoutDashboard, LogOut, MapPin, Menu, Plus, Search, Settings, Shield, Sparkles, Users, X } from 'lucide-react'
import { FormEvent, useEffect, useState } from 'react'
import { Link, Navigate, Outlet, useLocation, useNavigate } from 'react-router-dom'
import { isSupabaseReady, supabase } from '../lib/supabase'
import { faqs, locations, posts, programs, services } from '../data'

export function AdminLogin(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);const nav=useNavigate();async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');if(!supabase){setError('Supabase is not configured. Use secure preview mode to inspect the dashboard.');setLoading(false);return}const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(error.message);setLoading(false);return}if(data.session){localStorage.setItem('pawrexio_admin','authenticated');nav('/admin')}}function preview(){sessionStorage.setItem('pawrexio_admin_preview','true');nav('/admin')}return <main className="admin-login"><div className="login-brand"><img src="/assets/logo.png" alt="PAWREXIO"/><p>Management console</p></div><form onSubmit={submit}><p className="eyebrow">Secure admin access</p><h1>Welcome back.</h1><p>Sign in with an authorised PAWREXIO account.</p><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<p className="form-error">{error}</p>}<button className="button" disabled={loading}>{loading?'Signing in…':'Sign in'}</button><button type="button" className="preview-link" onClick={preview}>Preview dashboard without data access</button><Link to="/">← Return to website</Link><small>{isSupabaseReady?'Authentication is connected.':'Configuration mode · Add Supabase variables to enable live authentication.'}</small></form></main>}

const menu=[['Overview','/admin',LayoutDashboard],['Enquiries','/admin/enquiries',Inbox],['Services','/admin/services',Sparkles],['Programs','/admin/programs',Shield],['Locations','/admin/locations',MapPin],['Gallery','/admin/gallery',GalleryHorizontal],['Testimonials','/admin/testimonials',Users],['Blog','/admin/blog',BookOpen],['FAQs','/admin/faqs',HelpCircle],['Settings','/admin/settings',Settings]] as const
function canAccess(){return localStorage.getItem('pawrexio_admin')==='authenticated'||sessionStorage.getItem('pawrexio_admin_preview')==='true'}
export function AdminShell(){const [open,setOpen]=useState(false);const loc=useLocation();const nav=useNavigate();if(!canAccess())return <Navigate to="/admin/login" replace/>;async function logout(){await supabase?.auth.signOut();localStorage.removeItem('pawrexio_admin');sessionStorage.removeItem('pawrexio_admin_preview');nav('/admin/login')}return <div className="admin-shell"><aside className={open?'open':''}><div className="admin-logo"><img src="/assets/logo.png" alt=""/><span><b>PAWREXIO</b><small>ADMIN CONSOLE</small></span><button onClick={()=>setOpen(false)}><X/></button></div><nav>{menu.map(([n,p,I])=><Link className={loc.pathname===p?'active':''} to={p} key={p} onClick={()=>setOpen(false)}><I/>{n}</Link>)}</nav><div className="admin-side-bottom"><Link to="/"><Home/>View website</Link><button onClick={logout}><LogOut/>Sign out</button></div></aside><div className="admin-main"><header><button className="admin-menu" onClick={()=>setOpen(true)}><Menu/></button><label><Search/><input placeholder="Search admin"/></label><div><button><Bell/><i/></button><span className="avatar">PA</span><p><b>PAWREXIO Admin</b><small>{sessionStorage.getItem('pawrexio_admin_preview')?'Preview mode':'Administrator'}</small></p><ChevronDown/></div></header><Outlet/></div></div>}

export function AdminOverview(){const cards=[['Total enquiries','24','+8 this month',Inbox],['New leads','07','Needs attention',Users],['Active services',String(services.length),'Published',Sparkles],['Training programs',String(programs.length),'Published',Shield],['Journal posts',String(posts.length),'3 published',FileText],['Service areas',String(locations.length),'Active',MapPin]] as const;return <AdminPage title="Good morning" sub="Here is what needs your attention today."><div className="metric-grid">{cards.map(([a,b,c,I])=><div key={a}><span><I/></span><p>{a}</p><h2>{b}</h2><small>{c}</small></div>)}</div><div className="admin-overview-grid"><section className="admin-card"><div className="card-head"><div><h2>Recent enquiries</h2><p>Latest requests across all service areas</p></div><Link to="/admin/enquiries">View all</Link></div><AdminTable type="enquiries" compact/></section><section className="admin-card activity"><div className="card-head"><div><h2>Content health</h2><p>Published website content</p></div><BarChart3/></div>{[['Services',services.length,8],['Programs',programs.length,5],['Locations',locations.length,8],['Blog posts',posts.length,6]].map(([n,v,max])=><div className="health" key={String(n)}><div><span>{n}</span><b>{v} active</b></div><i><em style={{width:`${Number(v)/Number(max)*100}%`}}/></i></div>)}</section></div></AdminPage>}

const enquiries=[{name:'Ananya Mehta',pet:'Milo · Golden Retriever',service:'Puppy Foundations',city:'Gurugram',date:'20 Aug 2026',status:'New'},{name:'Rahul Nair',pet:'Koko · Indie',service:'Leash & City Skills',city:'Delhi',date:'19 Aug 2026',status:'Contacted'},{name:'Ishita Rao',pet:'Nova · Bengal Cat',service:'Cat Training',city:'Bengaluru',date:'18 Aug 2026',status:'Follow Up'},{name:'Kabir Shah',pet:'Bruno · Labrador',service:'Behaviour Modification',city:'Noida',date:'18 Aug 2026',status:'Booked'}]
function AdminTable({type,compact=false}:{type:string;compact?:boolean}){const rows=type==='enquiries'?enquiries:[];return <div className="table-wrap"><table><thead><tr>{['Client / Pet','Service','City','Received','Status',''].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.slice(0,compact?4:rows.length).map(r=><tr key={r.name}><td><b>{r.name}</b><small>{r.pet}</small></td><td>{r.service}</td><td>{r.city}</td><td>{r.date}</td><td><span className={`status ${r.status.toLowerCase().replace(' ','-')}`}>{r.status}</span></td><td><button>•••</button></td></tr>)}</tbody></table></div>}
export function AdminEnquiries(){return <AdminPage title="Enquiry CRM" sub="Review, qualify and follow up with every incoming lead." action="Export"><div className="admin-card"><div className="toolbar"><label><Search/><input placeholder="Search name, phone or pet"/></label><select><option>All statuses</option><option>New</option><option>Contacted</option><option>Booked</option></select><select><option>All locations</option>{locations.map(l=><option key={l.id}>{l.city}</option>)}</select></div><AdminTable type="enquiries"/></div></AdminPage>}

type Item={id:string;title?:string;city?:string;slug:string;status?:string}
export function AdminCollection({type}:{type:'services'|'programs'|'locations'|'blog'|'gallery'|'testimonials'|'faqs'}){const itemMap:Record<string,Item[]>={services:services.map(x=>({...x,status:'Published'})),programs:programs.map(x=>({...x,status:'Published'})),locations:locations.map(x=>({...x,title:x.city,status:'Active'})),blog:posts.map(x=>({...x,status:'Published'})),gallery:[],testimonials:[],faqs:faqs.map((x,i)=>({id:String(i),slug:String(i),title:x[0],status:'Published'}))};const labels:Record<string,string>={services:'Services',programs:'Training programs',locations:'Locations',blog:'Journal posts',gallery:'Gallery',testimonials:'Testimonials',faqs:'Frequently asked questions'};const items=itemMap[type];return <AdminPage title={labels[type]} sub={`Manage ${labels[type].toLowerCase()} shown across the PAWREXIO website.`} action={`Add ${type==='blog'?'post':type.slice(0,-1)}`}><div className="admin-card"><div className="toolbar"><label><Search/><input placeholder={`Search ${labels[type].toLowerCase()}`}/></label><select><option>All statuses</option><option>Published</option><option>Draft</option></select></div>{items.length?<div className="collection-list">{items.map((x,i)=><div key={x.id}><span className="row-index">{String(i+1).padStart(2,'0')}</span><div><b>{x.title}</b><small>/{x.slug}</small></div><span className="status published">{x.status}</span><button>Edit</button><button>•••</button></div>)}</div>:<div className="admin-empty"><GalleryHorizontal/><h3>No {labels[type].toLowerCase()} yet</h3><p>Add the first item when verified content is ready.</p><button className="button button-small"><Plus/>Add item</button></div>}</div></AdminPage>}
export function AdminSettings(){return <AdminPage title="Site settings" sub="Operational details shared across the website."><form className="admin-card settings-form"><h2>Contact & communication</h2><div className="field-row"><label>Public email<input defaultValue="hello@pawrexio.com"/></label><label>Phone number<input placeholder="Add verified number"/></label></div><label>WhatsApp number<input placeholder="Country code + number"/></label><h2>Brand & business</h2><div className="field-row"><label>Business name<input defaultValue="PAWREXIO"/></label><label>Tagline<input defaultValue="TRAIN • TRUST • TRANSFORM"/></label></div><label>Registered address<textarea placeholder="Add verified legal address before launch"/></label><div className="settings-actions"><button type="button" className="button">Save changes</button><span>Changes require a connected Supabase project.</span></div></form></AdminPage>}
function AdminPage({title,sub,action,children}:{title:string;sub:string;action?:string;children:React.ReactNode}){return <main className="admin-page"><div className="admin-title"><div><p className="eyebrow">PAWREXIO operations</p><h1>{title}</h1><p>{sub}</p></div>{action&&<button className="button button-small"><Plus/>{action}</button>}</div>{children}</main>}
