import { BarChart3, Bell, BookOpen, ChevronDown, FileText, GalleryHorizontal, Globe2, Home, Inbox, LayoutDashboard, LogOut, MapPin, Menu, Search, Settings, Shield, Sparkles, Users, X } from 'lucide-react'
import { CmsPage } from './Cms'
import { FormEvent, useState, useEffect } from 'react'
import { Link, Navigate, Outlet, useLocation, useNavigate } from 'react-router-dom'
import { isSupabaseReady, supabase } from '../lib/supabase'
import { locations, posts, programs, services } from '../data'

export function AdminLogin(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);const nav=useNavigate();async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');if(!supabase){setError('Supabase is not configured. Use secure preview mode to inspect the dashboard.');setLoading(false);return}const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(error.message);setLoading(false);return}if(data.session){sessionStorage.removeItem('pawrexio_admin_preview');localStorage.setItem('pawrexio_admin','authenticated');nav('/admin')}}function preview(){sessionStorage.setItem('pawrexio_admin_preview','true');nav('/admin')}return <main className="admin-login"><div className="login-brand"><img src="/assets/logo.png" alt="PAWREXIO"/><p>Management console</p></div><form onSubmit={submit}><p className="eyebrow">Secure admin access</p><h1>Welcome back.</h1><p>Sign in with an authorised PAWREXIO account.</p><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<p className="form-error">{error}</p>}<button className="button" disabled={loading}>{loading?'Signing in…':'Sign in'}</button><button type="button" className="preview-link" onClick={preview}>Preview dashboard without data access</button><Link to="/">← Return to website</Link><small>{isSupabaseReady?'Authentication is connected.':'Configuration mode · Add Supabase variables to enable live authentication.'}</small></form></main>}

const menu=[['Dashboard','/admin',LayoutDashboard],['Enquiries','/admin/enquiries',Inbox],['Services','/admin/services',Sparkles],['Packages','/admin/programs',Shield],['Blogs','/admin/blog',BookOpen],['Locations','/admin/locations',MapPin],['Gallery','/admin/gallery',GalleryHorizontal],['Testimonials','/admin/testimonials',Users],['SEO / Metadata','/admin/seo',Globe2],['Site Settings','/admin/settings',Settings]] as const
function canAccess(){return localStorage.getItem('pawrexio_admin')==='authenticated'||sessionStorage.getItem('pawrexio_admin_preview')==='true'}
export function AdminShell(){const [open,setOpen]=useState(false);const loc=useLocation();const nav=useNavigate();const [verified,setVerified]=useState(sessionStorage.getItem('pawrexio_admin_preview')==='true');const [checking,setChecking]=useState(!verified);useEffect(()=>{if(sessionStorage.getItem('pawrexio_admin_preview')==='true')return;let active=true;(async()=>{const {data}=await supabase?.auth.getUser()||{data:{user:null}};const result=data.user?await supabase!.from('profiles').select('role').eq('id',data.user.id).single():null;if(active){setVerified(['admin','editor'].includes(result?.data?.role||''));setChecking(false)}})();return()=>{active=false}},[]);if(checking)return <p className='cms-empty'>Checking secure session…</p>;if(!verified||!canAccess())return <Navigate to="/admin/login" replace/>;async function logout(){await supabase?.auth.signOut();localStorage.removeItem('pawrexio_admin');sessionStorage.removeItem('pawrexio_admin_preview');nav('/admin/login')}return <div className="admin-shell">{open&&<button className="admin-nav-backdrop" aria-label="Close sidebar" onClick={()=>setOpen(false)}/>}<aside className={open?'open':''}><div className="admin-logo"><img src="/assets/logo.png" alt=""/><span><b>PAWREXIO</b><small>ADMIN CONSOLE</small></span><button onClick={()=>setOpen(false)}><X/></button></div><nav>{menu.map(([n,p,I])=><Link className={loc.pathname===p?'active':''} to={p} key={p} onClick={()=>setOpen(false)}><I/>{n}</Link>)}</nav><div className="admin-side-bottom"><Link to="/"><Home/>View website</Link><button onClick={logout}><LogOut/>Sign out</button></div></aside><div className="admin-main"><header><button className="admin-menu" onClick={()=>setOpen(true)}><Menu/></button><Link to="/admin/enquiries">Enquiries & follow-ups</Link><div><span className="avatar">PA</span><p><b>PAWREXIO Admin</b><small>{sessionStorage.getItem('pawrexio_admin_preview')?'Preview mode':'Administrator'}</small></p><ChevronDown/></div></header><Outlet/></div></div>}

export function AdminOverview(){const [leadCounts,setLeadCounts]=useState({total:'—',fresh:'—'});useEffect(()=>{if(!supabase||sessionStorage.getItem('pawrexio_admin_preview'))return;void supabase.from('enquiries').select('status').then(({data,error})=>{if(!error&&data)setLeadCounts({total:String(data.length),fresh:String(data.filter(x=>x.status==='new').length)})},)},[]);const cards=[['Total enquiries',leadCounts.total,'Connect Supabase for live data',Inbox],['New leads',leadCounts.fresh,'No unverified sample data',Users],['Active services',String(services.length),'Published',Sparkles],['Training packages',String(programs.length),'Published',Shield],['Published blogs',String(posts.length),'Published',FileText],['Active locations',String(locations.length),'Published',MapPin]] as const;return <AdminPage title="Dashboard" sub="A focused view of enquiries, publishing and service coverage."><div className="metric-grid">{cards.map(([a,b,c,I])=><div key={a}><span><I/></span><p>{a}</p><h2>{b}</h2><small>{c}</small></div>)}</div><div className="admin-overview-grid"><section className="admin-card"><div className="card-head"><div><h2>Recent enquiries</h2><p>Live requests appear when Supabase is connected</p></div><Link to="/admin/enquiries">View all</Link></div><AdminTable/></section><section className="admin-card activity"><div className="card-head"><div><h2>Content health</h2><p>Published website content</p></div><BarChart3/></div>{[['Services',services.length],['Packages',programs.length],['Locations',locations.length],['Blog posts',posts.length]].map(([n,v])=><div className="health" key={String(n)}><div><span>{n}</span><b>{v} active</b></div><i><em style={{width:'100%'}}/></i></div>)}</section></div></AdminPage>}


function AdminTable(){return <p className="cms-empty">Open Enquiries to search, review and update live leads.</p>}
export function AdminEnquiries(){return <CmsPage type="enquiries"/>}
export function AdminCollection({type}:{type:'services'|'programs'|'locations'|'blog'|'gallery'|'testimonials'}){return <CmsPage key={type} type={type}/>}
export function AdminSeo(){return <CmsPage type="seo"/>}
export function AdminSettings(){return <CmsPage type="settings"/>}
function AdminPage({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <main className="admin-page"><div className="admin-title"><div><p className="eyebrow">PAWREXIO operations</p><h1>{title}</h1><p>{sub}</p></div></div>{children}</main>}
