import { Clock3, HeartPulse, MapPinned, Mail, MessageCircle, Phone } from 'lucide-react'
import { EnquiryVisual, HomeEnquiry } from '../components/HomeEnquiry'
import { PageHero, SectionTitle, whatsapp } from '../components/Layout'
import { siteSettings } from '../data'

export default function Contact(){return <>
 <PageHero eyebrow="" title="Contact Us" text="Have questions about breeds, availability, care, training or pricing? Send us your enquiry and our team will contact you shortly." image="/assets/real/puppy-focus.webp"/>
 <section className="contact-trust"><div className="container trust-inner">{[[Clock3,'Quick Response Support','Clear guidance when you need it.'],[HeartPulse,'Healthy, Pet-First Care','Every recommendation begins with wellbeing.'],[MapPinned,'Available Across India','Professional support in growing service areas.']].map(([Icon,label,text])=><article key={String(label)}>{typeof Icon!=='string'&&<i><Icon/></i>}<div><strong>{String(label)}</strong><small>{String(text)}</small></div></article>)}</div></section>
 <section className="section contact-enquiry"><div className="container"><div className="home-enquiry-grid"><EnquiryVisual contact/><HomeEnquiry contactCopy source="contact-page" originatingPage="/contact"/></div></div></section>
 <section className="section contact-details-section"><div className="container"><SectionTitle eyebrow="Contact Us" title="Let's Connect With You" text="We're ready to help with pet enquiries, bookings, training, care, availability and pricing."/><h2 className="contact-information-title">Contact Information</h2><div className="contact-detail-grid"><article><i><Phone/></i><small>Direct line</small><h3>Call Us</h3><a href={`tel:${siteSettings.phone}`}>{siteSettings.phone}</a></article><article><i><MessageCircle/></i><small>Quick support</small><h3>WhatsApp</h3><a href={whatsapp()} target="_blank" rel="noopener noreferrer">Talk to Pawrexio</a></article><article><i><Mail/></i><small>Write to us</small><h3>Email Address</h3><a href={`mailto:${siteSettings.email}`}>{siteSettings.email}</a></article><article><i><MapPinned/></i><small>Visit Pawrexio</small><h3>Office Location</h3><p>{siteSettings.address}</p></article></div><div className="contact-map"><div><p className="eyebrow">Find Us Here</p><h2>Pawrexio, Gurugram</h2><p>{siteSettings.address}</p></div><iframe title="Pawrexio office location on Google Maps" src="https://www.google.com/maps/embed?pb=%211m14%211m12%211m3%211d3427.078106193147%212d77.00192535876032%213d28.485254092115984%212m3%211f0%212f0%213f0%213m2%211i1024%212i768%214f13.1%215e0%213m2%211sen%212sin%214v1747651091728%215m2%211sen%212sin" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/></div></div></section>
 </>}
