import { Activity, ArrowRight, Award, BadgeCheck, CalendarClock, Cat, Check, Footprints, GraduationCap, Headphones, HeartHandshake, Home as HomeIcon, House, MessageCircle, Phone, Scissors, ShieldCheck, Stethoscope, Target, UserRoundCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { FAQList } from '../components/FAQ'
import { Hero } from '../components/Hero'
import { SectionTitle, whatsapp } from '../components/Layout'
import { LeadButton } from '../components/LeadPopup'
import { TrainingVideo } from '../components/Media'
import { Reveal } from '../components/Reveal'
import { faqs, locations, posts, programs, services, siteSettings, testimonials } from '../data'

const behaviours=[['Puppy habits','Toilet routines, biting, chewing and early manners.'],['Leash pulling','Calmer walks, useful check-ins and safe handling.'],['Obedience','Clear responses to sit, stay, come and settle.'],['Excessive barking','Understand triggers and build more appropriate responses.'],['Aggression & fear','Assessment-led support for reactivity and difficult behaviour.'],['Home training','Work on behaviour where it occurs every day.']]
const ownerTips=[
 [House,'Create a Safe Home','Prepare a comfortable, clean, and secure environment where your pet feels protected and relaxed.'],
 [GraduationCap,'Start Training Early','Early puppy training teaches good behaviour, basic commands, and builds lifelong confidence.'],
 [CalendarClock,'Follow a Routine','Regular feeding, exercise, sleep, and training help your pet adapt quickly.'],
 [Footprints,'Leash Training','Proper leash manners make walks enjoyable, safe, and improve overall obedience.'],
 [Activity,'Keep Them Active','Daily walks and exercise improve fitness, mental stimulation, and social behaviour.'],
 [Scissors,'Regular Grooming','Professional grooming keeps your pet clean, healthy, comfortable, and looking their best.'],
 [Cat,'Understand Your Cat','Encourage positive habits and better communication through expert cat training.'],
 [Award,'Reward Good Behaviour','Positive reinforcement using praise and treats helps pets learn faster.'],
 [Stethoscope,'Routine Vet Care','Regular health check-ups and vaccinations ensure a long, happy, and healthy life.']
] as const
const featuredSlugs=['puppy-training','basic-training-for-dog','smart-training-for-dog','canine-behaviour-training','kitten-training','bath--brush','proffesional-dog-walker']

export default function Home(){return <><Hero/>
 <section className="trust-strip"><div className="container trust-inner">{[[ShieldCheck,'Positive & humane'],[Target,'Personalised plans'],[HeartHandshake,'Stronger bonds'],[UserRoundCheck,'Pet-parent guidance']].map(([Icon,t])=><div key={String(t)}>{typeof Icon!=='string'&&<Icon/>}<span>{String(t)}</span></div>)}</div></section>
 <section className="section worldwide-section"><div className="container worldwide-grid"><Reveal className="worldwide-media"><img src="/assets/real/obedience.webp" alt="Pawrexio trainer working with a dog" loading="lazy"/></Reveal><Reveal><p className="eyebrow">Pawrexio</p><h2>Fast, certified &amp; trusted worldwide services</h2><p>Pawrexio is a leading provider of Pet Training, Puppy Training, and professional pet care services in India, dedicated to helping pet parents raise well-mannered, confident, and happy pets. With a strong focus on compassionate and positive training methods, Pawrexio has earned the trust of pet owners across the country.</p><p>From expert Leash Training for Dogs to personalized Cat Training Services, our certified trainers deliver effective solutions tailored to every pet’s behavior and needs. We also offer reliable Dog Walking Services, premium Pet Grooming Services, and convenient Dog Grooming at Home options to ensure complete care for your furry companions.</p><ul className="worldwide-benefits"><li><Check/>Transparent, reliable, and budget-friendly pricing</li><li><Check/>Positive, personalized training focused on measurable behavioural improvement.</li><li><Check/>Expert trainers with 24/7 dedicated online support</li></ul><Link className="button" to="/about">Know More <ArrowRight/></Link></Reveal></div></section>
 <section className="section services-home"><div className="container"><SectionTitle eyebrow="Training, care and companionship" title="Our services" text="Practical support for dogs, cats and the people who love them."/><div className="service-category-grid">{services.map((s,i)=><Reveal className="service-category" key={s.id}><span>{String(i+1).padStart(2,'0')}</span><img src={s.image} alt="" loading="lazy"/><div><p>{s.kicker}</p><h3>{s.title}</h3><small>{s.description}</small><div className="card-actions"><Link className="service-know-more" to={`/services/${s.slug}`}>Know more <ArrowRight/></Link><a className="icon-action" href={whatsapp(s.title)} target="_blank" rel="noreferrer" aria-label={`Ask about ${s.title} on WhatsApp`}><MessageCircle/></a></div></div></Reveal>)}</div><div className="center-action services-all-action"><Link className="button" to="/services">View All Services <ArrowRight/></Link></div></div></section>
 <section className="section program-section"><div className="container"><SectionTitle eyebrow="Training for every stage" title="Popular training packages" text="Compare proven starting points, then let consultation and assessment shape the final plan."/><div className="program-scroll">{featuredSlugs.map(slug=>programs.find(program=>program.slug===slug)).filter((program):program is NonNullable<typeof program>=>Boolean(program)).map((p,i)=><Reveal className="program-card" key={p.id}><div className="program-image"><img src={p.image} alt="" loading="lazy"/><span>0{i+1}</span></div><div className="program-body"><p className="program-category-badge">{p.category}</p><h3>{p.title}</h3><span>{p.summary}</span><ul>{p.includes.slice(0,4).map(x=><li key={x}><Check/>{x}</li>)}</ul><div className="card-actions"><Link to={`/packages/${p.slug}`}>View details <ArrowRight/></Link><Link className="button button-small" to={`/packages/${p.slug}`}>Check price</Link></div></div></Reveal>)}</div><div className="center-action"><Link className="button button-ghost" to="/packages">View all packages</Link></div></div></section>
 <section className="section behaviour-section"><div className="container"><div className="behaviour-head"><SectionTitle eyebrow="Pet behaviour & training" title="Is your pet struggling with these behaviours?" text="Behaviour is information. Understanding what drives it is the first step toward practical, lasting improvement."/><LeadButton service="Behaviour Training">Talk to a trainer</LeadButton></div><div className="behaviour-grid">{behaviours.map(([title,text],i)=><Reveal key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section>
 <section className="section why-copy-section"><div className="container"><Reveal className="why-copy-card"><p className="eyebrow">Why Choose Pawrexio?</p><p>At <strong>Pawrexio</strong>, we believe effective dog training and pet training is about more than teaching commands, it’s about understanding your pet and building a stronger bond between you and them. With 15+ years of experience, our professional pet trainers provide personalized dog training services based on your pet’s age, behaviour, breed, and individual needs. From puppy training and dog obedience training to leash training for dogs and behaviour correction, we focus on practical training that helps your pet become more confident, well-behaved, and easier to manage in everyday life. Whether you are looking for a professional dog trainer near you, dog training at home, or support with a specific behaviour concern, our goal is to give you the guidance and confidence to create a happier life with your pet.</p></Reveal></div></section>
 <section className="section pawrexio-story"><div className="container"><div className="story-opening"><p className="lead">The day a pet enters your home, they become more than just an animal, they become family. They celebrate your happiest moments, comfort you on difficult days, and love you without expecting anything in return. But unlike us, they can't tell us when they're anxious, confused, or trying to understand the world around them. Instead, they communicate through their behaviour.</p></div><div className="pawrexio-story-grid"><Reveal><p className="eyebrow">Pawrexio story</p><h2>That's Where We Come In</h2><p>With over 15+ years of experience, Pawrexio has helped thousands of pets and pet parents build stronger relationships through trust, patience, and positive training.</p><p>Whether it's a playful puppy learning basic manners, a dog struggling with behavioural challenges, or a pet that simply needs a little extra care, our Professional Dog Trainer in India is here to help.</p><p>From Professional Dog Trainer, Puppy Training, Dog Walking Services, Leash Training for Dogs, Pet Grooming Services, Cat Training Services, and Dog Grooming at Home, we believe every pet deserves to feel understood, loved, and confident.</p><div className="story-highlight"><h3>Transforming Pets into Happy, Well-Trained Companions</h3><p>At Pawrexio, we don't just train pets, we build lifelong friendships. Less stress, happier pets, and a stronger bond between you and your furry friend through positive, compassionate training.</p></div></Reveal><Reveal className="story-real-media"><img src="/assets/real/reward-training.webp" alt="Pawrexio positive pet training session" loading="lazy"/></Reveal></div><div className="trust-card-grid">{[[Award,'15+ Years Experience','Trusted by thousands of happy pet parents across India.'],[BadgeCheck,'5000+ Pets Trained','Professional training for dogs, puppies & cats.'],[HeartHandshake,'Positive Training','Reward-based methods that create confident pets.'],[Headphones,'24/7 Support','Always available to guide you through every step.']].map(([Icon,title,text])=><Reveal className="trust-card" key={String(title)}>{typeof Icon!=='string'&&<Icon/>}<h3>{String(title)}</h3><p>{String(text)}</p></Reveal>)}</div></div></section>
 <section className="section process"><div className="container"><SectionTitle eyebrow="Simple, structured, personal" title="Your training journey" center/><div className="process-line">{[[MessageCircle,'Consultation','Tell us about your pet and goals.'],[UserRoundCheck,'Assessment','We observe routines and triggers.'],[Target,'Custom plan','We recommend the right progression.'],[HomeIcon,'Training','Focused sessions build useful skills.'],[HeartHandshake,'Transformation','Daily practice turns skills into habits.']].map(([Icon,title,text],i)=><Reveal className="process-step" key={String(title)}><span>0{i+1}</span><i/><div>{typeof Icon!=='string'&&<Icon/>}</div><h3>{String(title)}</h3><p>{String(text)}</p></Reveal>)}</div></div></section>
 <section className="consult-band"><div className="container"><div><p className="eyebrow">Not sure what your pet needs?</p><h2>Tell us the issue and your location.</h2></div><div className="band-actions"><LeadButton>Get personalised guidance <ArrowRight/></LeadButton><a className="button button-ghost" href={whatsapp()} target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp</a></div></div></section>
 <section className="section first-owner-tips"><div className="container"><SectionTitle eyebrow="🐾 First-Time Pet Owner Tips" title="Everything You Need to Give Your Pet the Best Start" text="Becoming a pet parent is exciting and rewarding. With the right care, routine, training, and expert guidance, your furry companion can enjoy a happy, healthy, and confident life from day one."/><div className="owner-tip-grid">{ownerTips.map(([Icon,title,text],i)=><Reveal className="owner-tip-card" key={title}><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{text}</p></Reveal>)}</div><a className="text-link" href={`tel:${siteSettings.phone}`}><Phone/>Speak to our team</a></div></section>
 <section className="section location-preview"><div className="container"><SectionTitle eyebrow="Local pet support" title="Find Pawrexio near you" text="Explore current service areas and enquire with your locality for precise availability."/><div className="location-mini-grid">{locations.slice(0,6).map(l=><Link to={`/locations/${l.slug}`} key={l.id}><span>{l.state}</span><h3>{l.city}</h3><ArrowRight/></Link>)}</div><div className="center-action"><Link className="button button-ghost" to="/locations">View all locations</Link></div></div></section>
 <TrainingVideo/><section className="section gallery-preview"><div className="container"><SectionTitle eyebrow="Training in action" title="Care you can see"/><div className="gallery-strip">{['/assets/real/obedience.webp','/assets/real/puppy-focus.webp','/assets/real/cat-session.webp'].map((x,i)=><Link to="/gallery" key={x}><img src={x} alt={['Dog training session','Puppy training session','Cat training session'][i]} loading="lazy"/></Link>)}</div></div></section>
 <section className="section testimonials-home"><div className="container"><SectionTitle eyebrow="Customer feedback" title="Stories from pet parents"/><div className="testimonial-grid">{testimonials.slice(0,3).map((t,i)=><Reveal key={t.id}><span>“</span><p>{t.quote}</p><div><b>{t.name}</b><small>{t.pet||t.location}</small></div><em>0{i+1}</em></Reveal>)}</div><Link className="text-link" to="/testimonials">Read more feedback <ArrowRight/></Link></div></section>
 <section className="section blog-preview"><div className="container"><SectionTitle eyebrow="Pet-parent resources" title="Learn from the journal"/><div className="blog-mini-grid">{posts.slice(0,3).map(p=><Link to={`/blog/${p.slug}`} key={p.id}><img src={p.image} alt="" loading="lazy"/><p>{p.category} · {p.readTime}</p><h3>{p.title}</h3><span>Read article <ArrowRight/></span></Link>)}</div></div></section>
 <section className="section faq-home"><div className="container faq-grid"><SectionTitle eyebrow="Helpful answers" title="Pet-parent questions" text="Clear answers about training, grooming, walking and choosing the right support."/><FAQList items={faqs.slice(0,6)}/></div></section>
 <section className="final-cta"><div className="container"><p className="eyebrow">Training • Care • Better Together</p><h2>A happier home starts with one good conversation.</h2><p>Book a free consultation and find the right next step for your pet.</p><div><LeadButton>Book a free consultation</LeadButton><a className="button button-ghost" href={whatsapp()} target="_blank" rel="noreferrer">Chat on WhatsApp</a></div></div></section>
 </>}
