import { ArrowRight,Check,HeartHandshake,Home as HomeIcon,MessageCircle,ShieldCheck,Sparkles,Target,UserRoundCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { FAQList } from '../components/FAQ'
import { Hero } from '../components/Hero'
import { SectionTitle } from '../components/Layout'
import { Reveal } from '../components/Reveal'
import { faqs,programs,testimonials } from '../data'

export default function Home(){const behaviours=[['Puppy habits','Toilet routines, biting, chewing and early manners.'],['Leash pulling','Calmer walks, useful check-ins and safe handling.'],['Obedience','Clear responses to sit, stay, come and settle.'],['Excessive barking','Understand triggers and build more appropriate responses.'],['Aggression & fear','Assessment-led support for reactivity and difficult behaviour.'],['Home training','Work on behaviour where it occurs every day.']];return <><Hero/>
 <section className="trust-strip"><div className="container trust-inner">{[[ShieldCheck,'Positive & humane'],[Target,'Personalised plans'],[HeartHandshake,'Stronger bonds'],[UserRoundCheck,'Pet-parent guidance']].map(([Icon,t])=><div key={String(t)}>{typeof Icon!=='string'&&<Icon/>}<span>{String(t)}</span></div>)}</div></section>
 <section className="section warm-intro"><div className="container intro-grid"><Reveal><p className="eyebrow">Professional pet training in India</p><h2>Every pet deserves to be understood.</h2><p className="lead">Pets are family. Pawrexio helps families build confidence, communication and lifelong trust through personalised training and thoughtful care.</p><p>From puppy foundations and dog obedience to leash training, behaviour support, cat training, grooming and walking, our work is built around the individual animal—not a one-size-fits-all formula.</p><Link className="text-link" to="/about">Meet Pawrexio <ArrowRight/></Link></Reveal><Reveal className="intro-images"><img src="/assets/hero-companionship.webp" alt="Trainer with a dog and cat"/><div><b>10+ years</b><span>Reference-business experience</span></div></Reveal></div></section>
 <section className="section program-section"><div className="container"><SectionTitle eyebrow="Training for every stage" title="Our Training Programs" text="Choose a starting point, then let consultation and assessment shape the final plan. Session counts and prices are confirmed directly rather than guessed online."/><div className="program-scroll">{programs.slice(0,6).map((p,i)=><Reveal className="program-card" key={p.id}><div className="program-image"><img src={p.image} alt="" loading="lazy"/><span>0{i+1}</span></div><div className="program-body"><p>{p.level}</p><h3>{p.title}</h3><span>{p.summary}</span><ul>{p.includes.map(x=><li key={x}><Check/>{x}</li>)}</ul><Link to={`/packages/${p.slug}`}>View details <ArrowRight/></Link></div></Reveal>)}</div><div className="center-action"><Link className="button button-ghost" to="/packages">View all packages</Link></div></div></section>
 <section className="section behaviour-section"><div className="container"><div className="behaviour-head"><SectionTitle eyebrow="Pet behaviour & training" title="Is your pet struggling with these behaviours?" text="Behaviour is information. Understanding what drives it is the first step toward practical, lasting improvement."/><Link className="button" to="/book">Talk to a trainer</Link></div><div className="behaviour-grid">{behaviours.map(([title,text],i)=><Reveal key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section>
 <section className="section why-section"><div className="container why-grid"><Reveal className="why-image"><img src="/assets/hero-dog.webp" alt="Professional trainer working with a dog"/><i/></Reveal><Reveal><p className="eyebrow">Why choose Pawrexio</p><h2>Better training begins with better understanding.</h2><p>We combine positive reinforcement, practical routines and hands-on pet-parent guidance to make learning clear for everyone involved.</p><div className="why-points">{[['Customized Programs','Plans reflect age, behaviour, breed, home and goals.'],['Positive & Humane Methods','Training protects confidence and emotional wellbeing.'],['Trust & Strong Bond','Clear communication helps relationships grow.'],['Behaviour-Based Training','We address context and causes—not only symptoms.'],['Professional Trainers','Structured support with honest expectations.'],['Lifetime Guidance','Techniques you can continue in everyday life.']].map(([a,b])=><div key={a}><Sparkles/><span><b>{a}</b><small>{b}</small></span></div>)}</div><div className="verified-stats"><div><b>10+</b><span>Years of reference-business experience</span></div><div><b>5000+</b><span>Pets trained by the reference business</span></div></div></Reveal></div></section>
 <section className="section process"><div className="container"><SectionTitle eyebrow="Simple, structured, personal" title="Your training journey" center/><div className="process-line">{[[MessageCircle,'Consultation','Tell us about your pet, goals and everyday challenges.'],[UserRoundCheck,'Assessment','We observe behaviour, routines, triggers and learning history.'],[Target,'Custom Plan','Your trainer recommends the right service and progression.'],[HomeIcon,'Training','Focused sessions build useful skills in realistic settings.'],[HeartHandshake,'Transformation','Pet-parent practice turns new skills into daily habits.']].map(([Icon,title,text],i)=><Reveal className="process-step" key={String(title)}><span>0{i+1}</span><i/><div>{typeof Icon!=='string'&&<Icon/>}</div><h3>{String(title)}</h3><p>{String(text)}</p></Reveal>)}</div></div></section>
 <section className="consult-band"><div className="container"><div><p className="eyebrow">Not sure what training your pet needs?</p><h2>Tell us about your pet, the issue and your location.</h2></div><Link className="button" to="/book">Get personalised guidance <ArrowRight/></Link></div></section>
 <section className="section testimonials-home"><div className="container"><SectionTitle eyebrow="Customer feedback" title="Stories from pet parents" text="Feedback adapted from the owner-authorised reference business; entries remain admin manageable."/><div className="testimonial-grid">{testimonials.slice(0,3).map((t,i)=><Reveal key={t.id}><span>“</span><p>{t.quote}</p><div><b>{t.name}</b><small>{t.pet||t.location}</small></div><em>0{i+1}</em></Reveal>)}</div><Link className="text-link" to="/testimonials">Read more feedback <ArrowRight/></Link></div></section>
 <section className="section faq-home"><div className="container faq-grid"><SectionTitle eyebrow="Helpful answers" title="Pet-parent questions" text="Clear answers about training, grooming, walking and choosing the right support."/><FAQList items={faqs.slice(0,6)}/></div></section>
 <section className="final-cta"><div className="container"><p className="eyebrow">Training • Care • Better Together</p><h2>A happier home starts with one good conversation.</h2><p>Book a free consultation and find the right next step for your pet.</p><div><Link className="button" to="/book">Book a free consultation</Link><Link className="button button-ghost" to="/services">Explore services</Link></div></div></section></>}
