import { ArrowRight, Award, Check, Compass, HeartHandshake, ShieldCheck, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { faqs, locations, programs, services } from '../data'
import { FAQList } from '../components/FAQ'
import { Hero } from '../components/Hero'
import { Reveal } from '../components/Reveal'
import { SectionTitle } from '../components/Layout'

export default function Home(){return <>
 <Hero/>
 <section className="trust-strip"><div className="container trust-inner">{[[ShieldCheck,'Humane methods'],[Compass,'Personalised plans'],[HeartHandshake,'Parent guidance'],[Award,'Progress-led care']].map(([Icon,t])=><div key={String(t)}>{typeof Icon!=='string'&&<Icon/>}<span>{String(t)}</span></div>)}</div></section>
 <section className="section intro"><div className="container split"><Reveal className="intro-visual"><div className="portrait-frame"><img src="/assets/hero-dog.webp" alt="Trainer working calmly with a German Shepherd"/><div className="gold-stamp"><Sparkles/><span>Train with<br/>understanding</span></div></div></Reveal><Reveal><SectionTitle eyebrow="The PAWREXIO standard" title="A well-trained pet is not controlled. They are understood."/><p className="lead">Great training begins with observation—not commands. We look at the animal, the environment and the relationship before shaping a plan that fits real life.</p><p>Every session combines clear structure with humane, reward-led teaching. The result is practical progress you can continue at home, and a pet who learns with confidence.</p><Link className="text-link gold" to="/about">Our philosophy <ArrowRight/></Link><div className="intro-signature"><strong>TRAIN</strong><i/><strong>TRUST</strong><i/><strong>TRANSFORM</strong></div></Reveal></div></section>
 <section className="section services-home"><div className="container"><SectionTitle eyebrow="What we solve together" title="Training shaped around real life." text="Choose a focused service or begin with an assessment. Every recommendation starts with your pet—not a pre-set package."/><div className="service-editorial">{services.slice(0,4).map((s,i)=><Reveal className="service-row" key={s.id}><span className="service-num">0{i+1}</span><div><p>{s.kicker}</p><h3>{s.title}</h3></div><p>{s.description}</p><Link to={`/services/${s.slug}`} aria-label={`Explore ${s.title}`}><ArrowRight/></Link></Reveal>)}</div><Link className="button button-outline" to="/services">Explore every service</Link></div></section>
 <section className="section program-section"><div className="container"><SectionTitle eyebrow="Signature programs" title="A clear path. A considered pace." center/><div className="program-grid">{programs.map((p,i)=><Reveal className={`program-card p${i}`} key={p.id}><div className="program-image"><img src={p.image} alt=""/><span>{p.level}</span></div><div className="program-body"><div className="program-meta"><span>0{i+1}</span><span>{p.duration}</span></div><h3>{p.title}</h3><p>{p.summary}</p><ul>{p.includes.map(x=><li key={x}><Check/>{x}</li>)}</ul><Link className="text-link gold" to={`/programs/${p.slug}`}>View program <ArrowRight/></Link></div></Reveal>)}</div></div></section>
 <section className="section philosophy"><div className="container philosophy-grid"><Reveal><p className="eyebrow">Our training philosophy</p><blockquote>“Behaviour is information. Our job is to listen before we teach.”</blockquote></Reveal><Reveal><p>We replace guesswork with a repeatable process—observe patterns, lower unnecessary pressure, reinforce useful choices, then steadily increase real-world challenge.</p><div className="philosophy-points"><div><span>01</span><b>Clear, kind communication</b><p>We teach the animal what works instead of relying on fear or confusion.</p></div><div><span>02</span><b>Skills that travel</b><p>Training moves from quiet practice to the environments where you need it.</p></div><div><span>03</span><b>People are part of the plan</b><p>We coach your timing, technique and routines for progress between sessions.</p></div></div></Reveal></div></section>
 <section className="section process"><div className="container"><SectionTitle eyebrow="The PAWREXIO process" title="From uncertainty to a shared language."/><div className="process-line">{['Listen & understand','Observe behaviour','Design the plan','Train together','Guide the parent','Review progress'].map((x,i)=><Reveal className="process-step" key={x}><span>{String(i+1).padStart(2,'0')}</span><i/><h3>{x}</h3><p>{['Tell us what life looks like now—and what you want to change.','We look at context, triggers, health considerations and learning history.','Your goals become an achievable, welfare-led training roadmap.','Short, focused sessions build fluency without overwhelming your pet.','You learn how to reinforce the same clarity in everyday routines.','We adjust challenge, celebrate progress and plan lasting maintenance.'][i]}</p></Reveal>)}</div></div></section>
 <section className="section transformation"><div className="container transformation-grid"><div><p className="eyebrow">Real transformation</p><h2>Progress is not a dramatic before and after. It is a hundred calmer moments.</h2><p>Choosing to look back at you on a walk. Settling while guests arrive. Offering trust during grooming. These are the changes that make life together feel different.</p><Link className="button" to="/book">Start with an assessment</Link></div><div className="result-stories"><div><span>From</span><p>Pulling toward every distraction</p><span>To</span><p>Checking in and walking on a loose lead</p></div><div><span>From</span><p>Chaotic greetings at the door</p><span>To</span><p>A calm station and a predictable routine</p></div><div><span>From</span><p>Stress around handling</p><span>To</span><p>Cooperative care in manageable steps</p></div></div></div></section>
 <section className="section location-preview"><div className="container"><SectionTitle eyebrow="Where we work" title="Local training. Built for your environment." text="Active service areas are managed centrally and each program is adapted to the places your pet actually lives, walks and learns."/><div className="location-list">{locations.slice(0,6).map((l,i)=><Link to={`/locations/${l.slug}`} key={l.id}><span>{String(i+1).padStart(2,'0')}</span><h3>{l.city}</h3><p>{l.state}</p><ArrowRight/></Link>)}</div></div></section>
 <section className="section faq-home"><div className="container faq-grid"><SectionTitle eyebrow="Before we begin" title="Questions pet parents ask us." text="Still unsure where to start? Tell us what you are seeing and we’ll point you toward the right next step."/><FAQList items={faqs.slice(0,5)}/></div></section>
 <section className="final-cta"><div className="container"><p className="eyebrow">A better life together starts here</p><h2>Ready to transform your pet’s behaviour?</h2><p>Begin with a thoughtful conversation—no pressure, no one-size-fits-all promises.</p><div><Link className="button" to="/book">Book a training session</Link><Link className="button button-ghost" to="/contact">Talk to our team</Link></div></div></section>
 </>}
