import { ArrowRight, Check, MessageCircle } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { LeadButton } from '../components/LeadPopup'
import { PageHero, SectionTitle, whatsapp } from '../components/Layout'
import { programs } from '../data'

export function Programs(){return <><PageHero eyebrow="Training & care packages" title="A clear path for every stage." text="Compare dog training, cat training, walking and grooming packages. Verified sessions, durations and prices are shown where available; everything else is confirmed before booking."/><section className="section"><div className="container program-list">{programs.map((p,i)=><article key={p.id}><span className="giant-num">{String(i+1).padStart(2,'0')}</span><img src={p.image} alt="" loading="lazy"/><div><p className="eyebrow">{p.category} · {p.level}</p><h2>{p.title}</h2><p>{p.summary}</p>{(p.sessions||p.price)&&<div className="package-highlights">{p.sessions&&<span><b>Sessions</b>{p.sessions}</span>}{p.price&&<span><b>Price</b>{p.price}</span>}</div>}<ul>{p.includes.map(x=><li key={x}><Check/>{x}</li>)}</ul><div className="card-actions"><Link className="button button-outline" to={`/packages/${p.slug}`}>View details <ArrowRight/></Link><LeadButton className="button" service={p.title}>Check price</LeadButton><a className="icon-action" href={whatsapp(p.title)} target="_blank" rel="noreferrer" aria-label={`Ask about ${p.title} on WhatsApp`}><MessageCircle/></a></div></div></article>)}</div></section></>}

export function ProgramDetail(){const {slug}=useParams();const p=programs.find(x=>x.slug===slug);if(!p)return null;return <><PageHero eyebrow={`${p.category} · ${p.level}`} title={p.title} text={p.summary} image={p.image}/><section className="section"><div className="container detail-grid"><div className="detail-main"><SectionTitle eyebrow="Designed for useful change" title="What this package can include."/><div className="benefit-list">{p.includes.map(x=><div key={x}><Check/><span>{x}</span></div>)}</div><h2>Built around progress, not pressure</h2><p className="lead">Session pacing is adapted to your pet’s learning, emotional comfort and the complexity of your goals. Your trainer explains exactly what to practise between visits.</p><div className="quote-card">“The goal is a shared language your whole household can use—not a pet who responds only to the trainer.”</div></div><aside className="detail-aside"><p className="eyebrow">Package overview</p><dl><dt>Level</dt><dd>{p.level}</dd><dt>Duration</dt><dd>{p.duration}</dd><dt>Sessions</dt><dd>{p.sessions||'Confirmed after assessment'}</dd><dt>Price</dt><dd>{p.price||'Shared before booking'}</dd></dl><LeadButton className="button" service={p.title}>Book this service</LeadButton><a className="button whatsapp-action" href={whatsapp(p.title)} target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp</a></aside></div></section></>}
