import { ArrowRight, Check, MessageCircle } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { PageHero, SectionTitle, whatsapp } from '../components/Layout'
import { programs, services } from '../data'
import { PackageCards } from './Programs'
import { Breadcrumb } from '../components/Content'
import { LeadButton } from '../components/LeadPopup'

export function Services(){return <><PageHero eyebrow="Professional pet training & care" title="The right support for the life you share." text="From first routines to complex behaviour, grooming and dependable walks, every service is humane, practical and personalised."/><section className="section"><div className="container service-catalog">{services.map((s,i)=><article key={s.id}><div className="catalog-image"><img src={s.image} alt="" loading="lazy"/><span>{String(i+1).padStart(2,'0')}</span></div><div><p className="eyebrow">{s.category} · {s.kicker}</p><h2>{s.title}</h2><p>{s.description}</p><div className="catalog-meta"><span><b>Typical duration</b>{s.duration}</span><span><b>Best suited for</b>{s.suitable}</span></div><div className="card-actions"><Link className="button button-outline" to={`/services/${s.slug}`}>Know more <ArrowRight/></Link><a className="button whatsapp-action" href={whatsapp(s.title)} target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp</a></div></div></article>)}</div></section></>}

export function ServiceDetail(){const {slug}=useParams();const s=services.find(x=>x.slug===slug);if(!s)return null;const related=services.filter(x=>x.id!==s.id&&x.category===s.category).slice(0,3);return <><PageHero eyebrow={`${s.category} · ${s.kicker}`} title={s.title} text={s.description} image={s.image}/><Breadcrumb items={[{label:"Services",to:"/services"},{label:s.title}]}/>{["dog-training","cat-training","grooming","dog-walking"].includes(s.slug)&&<section className="section"><div className="container"><PackageCards items={programs.filter(p=>p.category===s.category)}/></div></section>}<section className="section"><div className="container detail-grid"><div className="detail-main"><SectionTitle eyebrow="Personalised support" title="Practical skills. Thoughtful progression."/>{s.content?.map(p=><p className="lead" key={p}>{p}</p>)}<div className="benefit-list">{(s.includes||s.benefits).map(x=><div key={x}><Check/><span>{x}</span></div>)}</div><h2>How the service works</h2><div className="detail-steps">{['Assessment & context','Skill building','Real-world practice','Parent coaching'].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3><p>{['We understand history, environment, routines and what success means to you.','Foundations are taught in manageable steps with clear reinforcement.','Skills are gradually practised around the distractions that matter.','You receive techniques and routines to maintain progress between sessions.'][i]}</p></div>)}</div></div><aside className="detail-aside"><p className="eyebrow">At a glance</p><dl><dt>Service</dt><dd>{s.title}</dd><dt>Typical duration</dt><dd>{s.duration}</dd><dt>Suitable for</dt><dd>{s.suitable}</dd><dt>Format</dt><dd>Home, outdoor or hybrid where available</dd><dt>Pricing</dt><dd>Shared after consultation</dd></dl><LeadButton className="button" service={s.title}>Book service</LeadButton><a className="button whatsapp-action" href={whatsapp(s.title)} target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp us</a></aside></div></section>{related.length>0&&<section className="section related"><div className="container"><SectionTitle eyebrow="Continue exploring" title="Related services"/><div className="related-grid">{related.map(x=><Link to={`/services/${x.slug}`} key={x.id}><img src={x.image} alt="" loading="lazy"/><h3>{x.title}</h3><p>{x.kicker}</p><ArrowRight/></Link>)}</div></div></section>}</>}
