import { useEffect,useState,useRef } from 'react'
import { ChevronDown,Facebook,Instagram,Linkedin,Mail,Menu,MessageCircle,Phone,Play,X } from 'lucide-react'
import { Link,NavLink,Outlet,useLocation } from 'react-router-dom'
import { services,siteSettings } from '../data'
import { LeadButton } from './LeadPopup'

const nav=[['Home','/'],['About Us','/about'],['Blogs','/blog'],['Gallery','/gallery'],['Locations','/locations'],['Feedback','/testimonials'],['Contact Us','/contact']]

export function whatsapp(context='pet training services'){const digits=(import.meta.env.VITE_WHATSAPP_NUMBER||siteSettings.whatsapp||'').replace(/\D/g,'');const n=digits.length===10?'91'+digits:digits;const msg=encodeURIComponent(`Hi Pawrexio, I would like to know more about ${context}.`);return `https://wa.me/${n}?text=${msg}`}

export function Layout(){
 const primary=services.filter(s=>['dog-training','cat-training','grooming','dog-walking'].includes(s.slug))
 const [open,setOpen]=useState(false),[servicesOpen,setServicesOpen]=useState(false),[scrolled,setScrolled]=useState(false);const loc=useLocation();const drawer=useRef<HTMLDivElement>(null);const toggle=useRef<HTMLButtonElement>(null)
 useEffect(()=>{const fn=()=>setScrolled(scrollY>18);addEventListener('scroll',fn);return()=>removeEventListener('scroll',fn)},[])
 useEffect(()=>{setOpen(false);setServicesOpen(false);scrollTo({top:0,behavior:'smooth'})},[loc.pathname])
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';drawer.current?.querySelector<HTMLElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);if(e.key==='Tab'){const els=[...drawer.current!.querySelectorAll<HTMLElement>('a,button')].filter(el=>el.getClientRects().length);const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key);toggle.current?.focus()}},[open])
 return <><a className="skip" href="#main">Skip to content</a><div className="topbar"><div className="container"><span>🐾 {siteSettings.strapline}</span><div><a href={`tel:${siteSettings.phone}`}><Phone/>{siteSettings.phone}</a><a href={`mailto:${siteSettings.email}`}><Mail/>{siteSettings.email}</a><a href={siteSettings.socials.facebook} aria-label="Facebook"><Facebook/></a><a href={siteSettings.socials.instagram} aria-label="Instagram"><Instagram/></a><a href={siteSettings.socials.youtube} aria-label="YouTube"><Play/></a>{siteSettings.socials.linkedin&&<a href={siteSettings.socials.linkedin} aria-label="LinkedIn"><Linkedin/></a>}</div></div></div>
 <header className={`site-header ${scrolled?'scrolled':''}`}><Link to="/" className="brand" aria-label="Pawrexio home"><img src="/assets/logo.png" alt="Pawrexio — Love, Care, Companionship"/></Link><nav className="desktop-nav" aria-label="Main navigation"><NavLink to="/" end>Home</NavLink><NavLink to="/about">About Us</NavLink><div className="nav-dropdown"><button onClick={()=>setServicesOpen(!servicesOpen)} aria-expanded={servicesOpen}>Services <ChevronDown/></button><div className={servicesOpen?'open':''}>{primary.map(s=><Link key={s.id} to={`/services/${s.slug}`}><span>{s.title}</span><small>{s.kicker}</small></Link>)}<Link to="/packages"><span>Training Packages</span><small>Compare every training pathway</small></Link></div></div>{nav.slice(2).map(([n,p])=><NavLink key={p} to={p}>{n}</NavLink>)}</nav><LeadButton className="button button-small header-cta">Book your service</LeadButton><a className="mobile-call" href={`tel:${siteSettings.phone}`} aria-label="Call Pawrexio"><Phone/></a><button ref={toggle} className="menu-button" onClick={()=>setOpen(true)} aria-expanded={open} aria-controls="mobile-navigation" aria-label="Open menu"><Menu/></button></header>
 {open&&<div className="nav-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div ref={drawer} id="mobile-navigation" className="mobile-drawer" role="dialog" aria-modal="true" aria-label="Mobile navigation"><div className="drawer-head"><b>Pawrexio</b><button onClick={()=>setOpen(false)} aria-label="Close menu"><X/></button></div><nav><NavLink to="/" end>Home</NavLink><NavLink to="/about">About Us</NavLink><button className="service-toggle" aria-expanded={servicesOpen} aria-controls="mobile-services" onClick={()=>setServicesOpen(!servicesOpen)}>Services <ChevronDown/></button>{servicesOpen&&<div id="mobile-services">{primary.map(s=><NavLink key={s.id} to={`/services/${s.slug}`}>{s.title}</NavLink>)}</div>}<NavLink to="/packages">Packages</NavLink>{nav.slice(2).map(([label,path])=><NavLink key={path} to={path}>{label}</NavLink>)}</nav><div className="drawer-actions"><div onClick={()=>setOpen(false)}><LeadButton>Book your service</LeadButton></div><a href={`tel:${siteSettings.phone}`}>Call {siteSettings.phone}</a><a href={whatsapp()} target="_blank" rel="noreferrer">WhatsApp</a></div></div></div>}
 <main id="main"><Outlet/></main><a className="whatsapp" href={whatsapp()} target="_blank" rel="noreferrer" aria-label="Talk to Pawrexio on WhatsApp"><MessageCircle/><span>WhatsApp us</span></a><div className="mobile-conversion" aria-label="Quick contact"><a href={`tel:${siteSettings.phone}`}><Phone/><span>Call</span></a><a href={whatsapp()} target="_blank" rel="noreferrer"><MessageCircle/><span>WhatsApp</span></a><LeadButton className="mobile-enquire"><Mail/><span>Enquire</span></LeadButton></div>
 <footer className="footer"><div className="footer-top"><div className="footer-brand"><img src="/assets/logo.png" alt="Pawrexio"/><p>{siteSettings.footer}</p><div className="socials"><a href={siteSettings.socials.facebook} aria-label="Facebook"><Facebook/></a><a href={siteSettings.socials.instagram} aria-label="Instagram"><Instagram/></a><a href={siteSettings.socials.youtube} aria-label="YouTube"><Play/></a>{siteSettings.socials.linkedin&&<a href={siteSettings.socials.linkedin} aria-label="LinkedIn"><Linkedin/></a>}</div></div><div><h4>Quick links</h4><Link to="/about">About Us</Link><Link to="/packages">Packages</Link><Link to="/gallery">Gallery</Link><Link to="/blog">Blogs</Link></div><div><h4>Our services</h4>{primary.map(s=><Link to={`/services/${s.slug}`} key={s.id}>{s.title}</Link>)}</div><div><h4>Company</h4><Link to="/locations">Locations</Link><Link to="/testimonials">Feedback</Link><Link to="/faq">FAQs</Link><Link to="/contact">Contact</Link></div><div><h4>Contact us</h4><a href={`tel:${siteSettings.phone}`}><Phone/>{siteSettings.phone}</a><a href={`mailto:${siteSettings.email}`}><Mail/>{siteSettings.email}</a><p>{siteSettings.address}</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Pawrexio. All Rights Reserved.</span><div><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms & Conditions</Link><Link to="/admin/login">Admin</Link></div></div></footer></>
}
export function PageHero({eyebrow,title,text,image='/assets/real/companions.webp'}:{eyebrow:string;title:string;text:string;image?:string}){return <section className="page-hero"><div className="container page-hero-grid"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lead">{text}</p></div><div className="page-hero-media"><img src={image} alt=""/><i/></div></div></section>}
export function SectionTitle({eyebrow,title,text,center=false}:{eyebrow:string;title:string;text?:string;center?:boolean}){return <div className={`section-title ${center?'center':''}`}><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
