import { Check, MessageCircle, X } from 'lucide-react'
import { createContext, FormEvent, PropsWithChildren, ReactNode, useCallback, useContext, useEffect, useRef, useState } from 'react'
import { useLocation } from 'react-router-dom'
import { siteSettings } from '../data'

type LeadContext={service?:string;package?:string;location?:string}
type LeadApi={openLead:(context?:LeadContext)=>void}
const PopupContext=createContext<LeadApi|null>(null)
export function useLeadPopup(){const value=useContext(PopupContext);if(!value)throw new Error('useLeadPopup must be used inside LeadPopupProvider');return value}
export function LeadButton({children,className='button',service,package:packageSlug,location}:{children:ReactNode;className?:string;service?:string;package?:string;location?:string}){const {openLead}=useLeadPopup();return <button type="button" className={className} onClick={()=>openLead({service,package:packageSlug,location})}>{children}</button>}

export function LeadPopupProvider({children}:PropsWithChildren){
 const {pathname}=useLocation();const [open,setOpen]=useState(false),[closing,setClosing]=useState(false),[context,setContext]=useState<LeadContext>({});const closeTimer=useRef<ReturnType<typeof setTimeout>>()
 const openLead=useCallback((next:LeadContext={})=>{clearTimeout(closeTimer.current);sessionStorage.setItem('pawrexio_popup_seen','1');setContext(next);setClosing(false);setOpen(true)},[])
 const close=useCallback(()=>{sessionStorage.setItem('pawrexio_popup_seen','1');setClosing(true);closeTimer.current=setTimeout(()=>{setOpen(false);setClosing(false)},280)},[])
 const blocked=/^\/(admin|login|auth|reset|reset-password)(\/|$)/.test(pathname)
 useEffect(()=>{if(blocked||open||sessionStorage.getItem('pawrexio_popup_seen'))return;const timer=setTimeout(()=>{sessionStorage.setItem('pawrexio_popup_seen','1');setContext({});setOpen(true)},4000);return()=>clearTimeout(timer)},[blocked,open])
 useEffect(()=>()=>clearTimeout(closeTimer.current),[])

 return <PopupContext.Provider value={{openLead}}>{children}{!blocked&&open&&<LeadPopup context={context} closing={closing} close={close}/>}</PopupContext.Provider>
}

function LeadPopup({context,closing,close}:{context:LeadContext;closing:boolean;close:()=>void}){
 const dialog=useRef<HTMLDivElement>(null),returnFocus=useRef<HTMLElement|null>(document.activeElement as HTMLElement|null)
 const [form,setForm]=useState({fullName:'',phone:'',email:'',service:context.service||context.package||'',city:context.location||'',concern:'',website:''})
 const [status,setStatus]=useState<'idle'|'loading'|'success'|'error'>('idle'),[error,setError]=useState('')
 const waMessage=encodeURIComponent(form.service&&form.city?`Hi Pawrexio, I am interested in ${form.service} for my pet in ${form.city}. Please share the details.`:'Hi Pawrexio, I need help choosing the right service for my pet.')
 const digits=(import.meta.env.VITE_WHATSAPP_NUMBER||siteSettings.whatsapp||'').replace(/\D/g,'');const waNumber=digits.length===10?'91'+digits:digits
 const successTimer=useRef<ReturnType<typeof setTimeout>>()
 useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow='hidden';setTimeout(()=>dialog.current?.querySelector<HTMLElement>('button,input,select,textarea,a')?.focus(),30);return()=>{clearTimeout(successTimer.current);document.body.style.overflow=previous;returnFocus.current?.focus()}},[])
 function keydown(e:React.KeyboardEvent){if(e.key==='Escape'){e.preventDefault();close();return}if(e.key!=='Tab'||!dialog.current)return;const items=[...dialog.current.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled])')];if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
 async function submit(e:FormEvent){e.preventDefault();if(status==='loading')return;setStatus('loading');setError('');try{const response=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName:form.fullName,phone:form.phone,email:form.email,city:form.city||'Not specified',petType:'Not specified',petName:'',breed:'',petAge:'',service:form.service||'not-sure',concern:form.concern||'Consultation requested through the website popup.',preferredDate:'',preferredTime:'',message:form.concern,website:form.website,source:'popup',originatingPage:location.pathname,packageSlug:context.package||''})});const body=await response.json();if(!response.ok)throw new Error(body.message||'Unable to send enquiry');setStatus('success');setForm({fullName:'',phone:'',email:'',service:'',city:'',concern:'',website:''});successTimer.current=setTimeout(close,1400)}catch(err){setError(err instanceof Error?err.message:'Unable to send your enquiry.');setStatus('error')}}
 return <div className={`lead-backdrop ${closing?'closing':''}`} onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div ref={dialog} className="lead-dialog legacy-contact-popup" role="dialog" aria-modal="true" aria-labelledby="lead-title" onKeyDown={keydown}><button className="lead-close" type="button" onClick={close} aria-label="Close consultation form"><X/></button><section className="lead-content">{status==='success'?<div className="lead-success"><i><Check/></i><p className="eyebrow">Enquiry received</p><h2 id="lead-title">Thank you!</h2><p>Our team will contact you shortly to understand your pet and recommend the right service.</p><div><a className="button whatsapp-action" href={`https://wa.me/${waNumber}?text=${waMessage}`} target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp now</a><button className="button button-outline" type="button" onClick={close}>Close</button></div></div>:<><h2 id="lead-title">Contact Us</h2><form className="lead-form" onSubmit={submit}><label><span className="sr-only">Your Name</span><input aria-label="Your Name" placeholder="Your Name" autoComplete="name" required minLength={2} maxLength={100} value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label><span className="sr-only">Phone Number</span><input aria-label="Phone Number" placeholder="Phone Number" autoComplete="tel" type="tel" required minLength={7} maxLength={25} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label><span className="sr-only">Email Address</span><input aria-label="Email Address" placeholder="Email Address" autoComplete="email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label><span className="sr-only">Your Message</span><textarea aria-label="Your Message" placeholder="Your Message" maxLength={500} value={form.concern} onChange={e=>setForm({...form,concern:e.target.value})}/></label><input className="honeypot" tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/>{status==='error'&&<p className="form-error" role="alert">{error}</p>}<button className="button lead-submit" disabled={status==='loading'}>{status==='loading'?'Sending…':'Submit'}</button></form></>}</section></div></div>
}
