import { z } from 'zod'
export type Field={key:string;label:string;type?:'text'|'textarea'|'content'|'list'|'number'|'select'|'boolean'|'image'|'datetime-local';options?:string[];required?:boolean}
const field=(key:string,label:string,type:Field['type']='text',required=false,options?:string[]):Field=>({key,label,type,required,options})
const seo=[field('seo_title','Meta title'),field('seo_description','Meta description','textarea'),field('canonical_url','Canonical URL'),field('og_image_url','Social preview image','image'),field('robots_index','Allow search indexing','boolean')]
const common=[field('title','Title','text',true),field('slug','Slug','text',true),field('category','Category','select',false,['Dog Training','Cat Training','Grooming','Dog Walking']),field('image_url','Featured image','image'),field('duration','Duration'),field('session_count','Sessions'),field('price_from','Price','number'),field('sale_price','Sale price','number'),field('inclusions','Inclusions (one per line)','list'),field('additional_images','Additional images (one URL per line)','list'),field('related_slugs','Related service slugs','list'),field('sort_order','Display order','number'),field('status','Status','select',false,['draft','published','archived']),...seo]
export const statuses=['new','contacted','follow_up','qualified','booked','completed','lost']
export const definitions:Record<string,{label:string;table:string;fields:Field[]}>= {
 services:{label:'Services',table:'services',fields:[...common,field('kicker','Subtitle'),field('short_description','Short description','textarea',true),field('description','Overview','textarea',true),field('content','Full content','content'),field('suitable_for','Suitable for'),field('benefits','Benefits','list')]},
 programs:{label:'Packages',table:'training_programs',fields:[...common,field('level','Level'),field('summary','Summary','textarea',true),field('description','Description','textarea'),field('content','Full content','content')]},
 locations:{label:'Locations',table:'locations',fields:[field('city','City','text',true),field('state','State','text',true),field('slug','Slug','text',true),field('heading','Page heading'),field('intro','Excerpt','textarea',true),field('content','City content','content'),field('image_url','Featured image','image'),field('available_services','Available service slugs','list'),field('sort_order','Display order','number'),field('active','Active','boolean'),...seo]},
 blog:{label:'Blogs',table:'blog_posts',fields:[field('title','Title','text',true),field('slug','Slug','text',true),field('excerpt','Excerpt','textarea',true),field('content','Article content','textarea',true),field('category','Category'),field('tags','Tags (one per line)','list'),field('author_name','Author display name'),field('published_at','Publish date','datetime-local'),field('featured_image_url','Featured image','image'),field('status','Status','select',false,['draft','published','archived']),...seo]},
 gallery:{label:'Gallery',table:'gallery',fields:[field('title','Title','text',true),field('image_url','Image / video URL','image',true),field('media_type','Media type','select',false,['image','video']),field('poster_url','Video poster','image'),field('caption','Caption','textarea'),field('category','Category'),field('sort_order','Display order','number'),field('active','Visible','boolean')]},
 testimonials:{label:'Testimonials',table:'testimonials',fields:[field('customer_name','Customer name','text',true),field('pet_name','Pet name'),field('location','Location'),field('content','Feedback','textarea',true),field('rating','Rating (1–5)','number'),field('image_url','Image','image'),field('verified','Verified','boolean'),field('active','Visible','boolean'),field('sort_order','Order','number')]},
 seo:{label:'SEO / Metadata',table:'seo_metadata',fields:[field('page_key','Page path','text',true),field('meta_title','Meta title','text',true),field('meta_description','Meta description','textarea',true),field('canonical_url','Canonical URL'),field('og_title','Social title'),field('og_description','Social description'),field('og_image_url','Social image','image'),field('robots_index','Allow indexing','boolean')]},
 settings:{label:'Site Settings',table:'site_settings',fields:[field('site_title','Site title'),field('tagline','Tagline'),field('public_email','Public email'),field('phone','Phone'),field('alternate_phone','Alternate phone'),field('whatsapp_number','WhatsApp (with country code)'),field('address','Address','textarea'),field('footer_text','Footer','textarea'),field('default_meta_title','Default meta title'),field('default_meta_description','Default meta description','textarea'),field('default_og_image_url','Default social image','image'),field('facebook','Facebook URL'),field('instagram','Instagram URL'),field('youtube','YouTube URL'),field('linkedin','LinkedIn URL')]},
 enquiries:{label:'Enquiries',table:'enquiries',fields:[field('full_name','Name','text',true),field('phone','Phone','text',true),field('email','Email'),field('city','City'),field('pet_type','Pet type'),field('service_slug','Service'),field('package_slug','Package'),field('source','Lead source'),field('originating_page','Originating page'),field('behaviour_concern','Concern','textarea'),field('status','Status','select',false,statuses),field('internal_notes','Internal notes','textarea'),field('follow_up_at','Follow-up date','datetime-local')]}
}
export function schemaFor(key:string){const def=definitions[key];if(!def)throw new Error('Unknown resource');const shape:Record<string,z.ZodTypeAny>={};for(const f of def.fields){let validator:z.ZodTypeAny=f.type==='boolean'?z.boolean():f.type==='number'?z.number().nonnegative().nullable():f.type==='list'?z.array(z.string().max(2000)).max(100):f.type==='content'?z.array(z.object({kind:z.enum(['heading','paragraph','list']),text:z.string().max(10000)})).max(300):f.type==='select'?z.enum(f.options as [string,...string[]]):z.string().max(f.type==='textarea'?100000:2000);if(f.required&&f.type!=='number')validator=z.string().trim().min(1).max(100000);if(f.key==='slug')validator=z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/,'Use lowercase words separated by hyphens');if(f.type==='image'||f.key==='canonical_url'||['facebook','instagram','youtube','linkedin'].includes(f.key))validator=z.string().max(2000).refine(v=>!v||/^https?:\/\//i.test(v)||/^\/(?!\/)/.test(v),'Use an https URL or local /assets path');shape[f.key]=validator.optional()}return z.object(shape).strict()}
