import type { BlogPost, Location, Program, Service, Testimonial } from './types'

export const siteSettings={strapline:'Smarter Pets. Happier You.',phone:'9211630927',alternatePhone:'',email:'Pets.heart2025@gmail.com',whatsapp:'9211630927',address:'Shop No. 6, TBS Road, near Krishna Chowk, Ashok Vihar Phase III Extension, Gurugram, Haryana 122001',socials:{facebook:'#',instagram:'#',youtube:'#',linkedin:'#'},footer:'Positive, personalised pet training and care that strengthens the bond between pets and their families.'}
const dog='/assets/hero-dog.webp',puppy='/assets/hero-puppy.webp',cat='/assets/hero-cat.webp'
export const services:Service[]=[
 {id:'dog',slug:'dog-training',title:'Dog Training',kicker:'Professional training for everyday life',description:'Personalised dog training for puppies and adult dogs, from household manners and obedience to leash skills and complex behaviour support.',icon:'dog',duration:'Plan confirmed after consultation',suitable:'Puppies and adult dogs',benefits:['Clear everyday communication','Positive, practical routines','Pet-parent coaching'],includes:['Puppy and obedience foundations','Leash and recall skills','Behaviour-based programs'],content:['Effective dog training is about more than teaching commands. It helps your dog understand what is expected while giving you a reliable way to guide them at home and outdoors.','Every plan considers age, breed, learning history, home routine and the situations where behaviour becomes difficult. Skills are taught progressively and practised in the real environments where you need them.'],image:dog,category:'Dog Training'},
 {id:'cat',slug:'cat-training',title:'Cat Training',kicker:'Positive guidance for curious cats',description:'Feline-friendly training for litter habits, scratching, handling, routines and enrichment—without force or intimidation.',icon:'cat',duration:'Plan confirmed after consultation',suitable:'Kittens and adult cats',benefits:['Better home habits','Handling confidence','Healthy enrichment'],includes:['Litter and home routines','Target and recall foundations','Scratching and handling guidance'],content:['Cats learn through association, choice and rewards. A thoughtful plan can improve litter habits, reduce unwanted scratching and make everyday handling easier.','Sessions focus on the environment as much as the cat, helping pet parents provide suitable outlets for climbing, play, rest and natural behaviour.'],image:cat,category:'Cat Training'},
 {id:'groom',slug:'grooming',title:'Pet Grooming',kicker:'Comfort, hygiene and coat care',description:'Professional bathing, brushing, trimming and hygiene care for dogs and cats, with convenient at-home options where available.',icon:'scissors',duration:'Depends on coat and service',suitable:'Dogs and cats',benefits:['Coat and skin upkeep','Nail, ear and hygiene care','Low-stress handling'],includes:['Bathing and drying','Brushing and de-shedding','Nail and ear care'],content:['Regular grooming supports skin health, coat condition and comfort. It also creates an opportunity to notice changes that may need veterinary attention.','Service scope depends on coat, size, condition and handling needs. The final recommendation is confirmed before the appointment.'],image:puppy,category:'Grooming'},
 {id:'walk',slug:'dog-walking',title:'Dog Walking',kicker:'Healthy movement and calmer routines',description:'Reliable dog walking that supports physical activity, mental stimulation and better neighbourhood manners.',icon:'route',duration:'Duration selected at booking',suitable:'Dogs needing consistent exercise',benefits:['Appropriate daily activity','Mental stimulation','Calmer walking routines'],includes:['Individual walking plan','Basic leash reinforcement','Visit update'],content:['A good walk is more than exercise. Sniffing, exploring and calmly navigating the neighbourhood contribute to physical health and emotional wellbeing.','Walking plans consider age, fitness, weather, route safety and existing leash skills. Training support can be added when pulling or reactivity makes walks difficult.'],image:dog,category:'Dog Walking'},
 {id:'puppy',slug:'puppy-training',title:'Puppy Training',kicker:'Build the right habits early',description:'House routines, social confidence, bite inhibition and first cues for a happy, well-mannered companion.',icon:'sparkles',duration:'Details on consultation',suitable:'Young puppies and first-time pet parents',benefits:['Toilet and sleep routines','Early obedience','Safe socialisation'],image:puppy,category:'Dog Training'},
 {id:'leash',slug:'leash-training-for-dogs',title:'Leash Training for Dogs',kicker:'Better walks, better communication',description:'Practical loose-leash skills, check-ins and calmer responses around everyday distractions.',icon:'route',duration:'Details on consultation',suitable:'Dogs that pull or struggle on walks',benefits:['Reduced pulling','Safer handling','Improved focus'],image:dog,category:'Dog Training'},
 {id:'behaviour',slug:'canine-behaviour-training',title:'Canine Behaviour Training',kicker:'Understand the reason behind behaviour',description:'Assessment-led support for barking, fear, anxiety, reactivity, guarding and difficult household patterns.',icon:'brain',duration:'Assessment-led',suitable:'Dogs with behaviour concerns',benefits:['Trigger assessment','Management strategies','Progressive behaviour plan'],image:dog,category:'Dog Training'},
 {id:'walker',slug:'professional-dog-walker',title:'Professional Dog Walker',kicker:'Consistent care while you are busy',description:'Scheduled, responsible walks tailored to your dog’s energy, comfort and neighbourhood.',icon:'route',duration:'Selected at booking',suitable:'Adult dogs and suitable puppies',benefits:['Routine exercise','Supervised outdoor time','Visit updates'],image:dog,category:'Dog Walking'},
 {id:'bath',slug:'bath-and-brush',title:'Bath & Brush',kicker:'Everyday coat care',description:'Bathing, brushing and drying selected for your pet’s coat and comfort.',icon:'scissors',duration:'Depends on pet size and coat',suitable:'Dogs and cats',benefits:['Clean coat','Reduced loose hair','Comfort-focused handling'],image:puppy,category:'Grooming'},
 {id:'tick',slug:'tick-treatment-bath-brush',title:'Tick Treatment With Bath & Brush',kicker:'Targeted coat and hygiene care',description:'A grooming service combining bath and brush care with an appropriate tick-care protocol.',icon:'scissors',duration:'Confirmed before service',suitable:'Pets requiring coat and tick care',benefits:['Coat cleansing','Thorough brushing','Care guidance'],image:puppy,category:'Grooming'},
 {id:'haircut',slug:'haircut-and-styling',title:'Haircut & Styling',kicker:'Breed and coat-aware styling',description:'Practical trimming and styling tailored to coat type, condition and pet comfort.',icon:'scissors',duration:'Depends on coat and style',suitable:'Suitable dog and cat coats',benefits:['Manageable coat','Hygiene trimming','Comfortable finish'],image:puppy,category:'Grooming'},
 {id:'litter',slug:'litter-training-for-cat',title:'Litter Training for Cat',kicker:'Calmer, cleaner home routines',description:'Environmental and reward-based guidance for litter-box use and related household habits.',icon:'cat',duration:'Details on consultation',suitable:'Kittens and adult cats',benefits:['Appropriate setup','Habit support','Pet-parent guidance'],image:cat,category:'Cat Training'}]

export const programs:Program[]=[
 {id:'p1',slug:'puppy-training',title:'Puppy Training',level:'Early foundations',duration:'Details on consultation',summary:'Build toilet habits, name response, handling confidence, socialisation and first household manners.',includes:['Healthy routines','Bite inhibition guidance','First cues and recall'],image:puppy,category:'Dog Training'},
 {id:'p2',slug:'basic-dog-training',title:'Basic Training for Dog',level:'Everyday obedience',duration:'Details on consultation',summary:'Essential communication and manners for a calmer, more manageable companion.',includes:['Sit, down and stay','Recall foundations','Household manners'],image:dog,category:'Dog Training'},
 {id:'p3',slug:'intermediate-dog-training',title:'Intermediate Dog Training',level:'Building reliability',duration:'Details on consultation',summary:'Strengthen known skills around distance, duration and everyday distractions.',includes:['Improved recall','Impulse control','Distraction practice'],image:dog,category:'Dog Training'},
 {id:'p4',slug:'smart-dog-training',title:'Smart Training for Dog',level:'Confident life skills',duration:'Details on consultation',summary:'Develop focus, responsive handling and useful skills for modern family life.',includes:['Advanced engagement','Door and visitor manners','Public-space skills'],image:dog,category:'Dog Training'},
 {id:'p5',slug:'advanced-dog-training',title:'Advanced Training for Dog',level:'Advanced obedience',duration:'Details on consultation',summary:'Progress fluent skills and handler communication in more challenging environments.',includes:['Advanced cues','Longer-distance control','Complex distraction work'],image:dog,category:'Dog Training'},
 {id:'p6',slug:'master-dog-training',title:'Master Training for Dog',level:'Complete development',duration:'Details on consultation',summary:'A comprehensive pathway tailored after assessment to broad behaviour and lifestyle goals.',includes:['Personalised curriculum','Real-world proofing','Pet-parent coaching'],image:dog,category:'Dog Training'},
 {id:'p7',slug:'basic-cat-training',title:'Basic Cat Training',level:'Home foundations',duration:'Details on consultation',summary:'Support litter habits, handling, scratching choices and responsive routines.',includes:['Litter guidance','Handling confidence','Home enrichment'],image:cat,category:'Cat Training'},
 {id:'p8',slug:'premium-dog-walking',title:'Premium Dog Walking Package',level:'Walking & enrichment',duration:'Morning and evening · Sunday off',sessions:'2 walks daily',price:'₹14,000 / month',summary:'A consistent twice-daily walking plan with hour-long morning and evening walks.',includes:['One-hour morning walk','One-hour evening walk','Routine and activity support'],image:dog,category:'Dog Walking'},
 {id:'p9',slug:'kitten-training',title:'Kitten Training',level:'Early cat foundations',duration:'30 minutes each',sessions:'12 sessions',price:'₹7,999',summary:'Positive early training for litter habits, biting, social etiquette and simple cues.',includes:['Litter-box training','Biting guidance','Sit and stay foundations'],image:cat,category:'Cat Training'},
 {id:'p10',slug:'smart-cat-training',title:'Smart Cat Training',level:'Responsive home skills',duration:'Details on consultation',summary:'Build engagement, handling confidence and useful home routines through feline-friendly reinforcement.',includes:['Target training','Recall foundations','Calm handling routines'],image:cat,category:'Cat Training'},
 {id:'p11',slug:'advanced-cat-training',title:'Advanced Cat Training',level:'Advanced feline skills',duration:'Details on consultation',summary:'Progress confident cats into more reliable cues, enrichment tasks and cooperative care.',includes:['Advanced target work','Cooperative care','Enrichment skills'],image:cat,category:'Cat Training'},
 {id:'p12',slug:'canine-behaviour-therapy',title:'Canine Behaviour Therapy (CBT)',level:'Behaviour support',duration:'4 months',sessions:'48 sessions',price:'₹46,000',summary:'Assessment-led support for aggression, anxiety, barking, fear, pulling and other complex behaviour concerns.',includes:['Trigger and behaviour assessment','Positive behaviour modification','Home management and parent guidance'],image:dog,category:'Dog Training'},
 {id:'p13',slug:'standard-dog-walking',title:'Standard Dog Walking Package',level:'Daily activity',duration:'Confirmed by locality',summary:'Reliable scheduled walking that supports fitness, enrichment and a calmer daily routine.',includes:['Planned neighbourhood walk','Basic leash reinforcement','Visit update'],image:dog,category:'Dog Walking'},
 {id:'p14',slug:'bath-brush',title:'Bath & Brush',level:'Essential grooming',duration:'Depends on size and coat',summary:'Comfort-focused bathing, drying and brushing for a cleaner, healthier coat.',includes:['Pet-safe bath','Drying and brushing','Basic hygiene check'],image:puppy,category:'Grooming'},
 {id:'p15',slug:'tick-treatment-bath-brush',title:'Tick Treatment With Bath & Brush',level:'Targeted coat care',duration:'Confirmed before service',summary:'Bath and brush care combined with an appropriate tick-care protocol.',includes:['Coat cleansing','Thorough brushing','After-care guidance'],image:puppy,category:'Grooming'},
 {id:'p16',slug:'haircut-styling',title:'Haircut & Styling',level:'Coat styling',duration:'Depends on coat and style',summary:'Practical trimming and styling tailored to coat type, condition and pet comfort.',includes:['Consulted haircut','Hygiene trimming','Comfortable finish'],image:puppy,category:'Grooming'},
 {id:'p17',slug:'bath-haircut-styling',title:'Bath, Haircut & Styling',level:'Complete groom',duration:'Depends on size and coat',summary:'A complete grooming appointment combining bathing, coat preparation, haircut and styling.',includes:['Bath and dry','Haircut and hygiene trim','Finishing brush and style'],image:puppy,category:'Grooming'},
 {id:'p18',slug:'massage-bath-full-haircut-styling',title:'Massage, Bath, Full Haircut & Styling',level:'Premium groom',duration:'Confirmed before service',summary:'A more comprehensive grooming experience designed around coat condition and pet comfort.',includes:['Comfort-focused massage','Bath and complete haircut','Full finishing and styling'],image:puppy,category:'Grooming'}]

const loc=(id:string,slug:string,city:string,state:string,intro:string):Location=>({id,slug,city,state,intro,heading:`Professional pet training in ${city}`,content:[`Life in ${city} presents its own training challenges, from apartment entrances and busy streets to visitors and neighbourhood walks. Pawrexio plans sessions around the environments your pet uses every day.`,`Available services may include puppy training, obedience, leash guidance, behaviour support, cat training, grooming and dog walking. Coverage and trainer availability are confirmed for your locality before booking.`]})
export const locations:Location[]=[loc('1','gurgaon','Gurgaon','Haryana','Personalised home and outdoor training for confident pets and calmer family routines.'),loc('2','hyderabad','Hyderabad','Telangana','Practical training for puppies, family dogs and pet parents across Hyderabad.'),loc('3','ahmedabad','Ahmedabad','Gujarat','Reward-led pet training adapted to busy homes and neighbourhood environments.'),loc('4','pune','Pune','Maharashtra','Positive training for puppies, adult dogs, cats and modern urban households.'),loc('5','chandigarh','Chandigarh','Chandigarh','Structured behaviour and obedience support for everyday family life.'),loc('6','bengaluru','Bengaluru','Karnataka','Training and enrichment shaped for apartment living and active city routines.'),loc('7','delhi','Delhi','Delhi','Professional pet training for reliable cues, calmer walks and better home habits.'),loc('8','mumbai','Mumbai','Maharashtra','Flexible pet support designed around compact homes and fast-paced city life.'),loc('9','delhi-ncr','Delhi NCR','Delhi NCR','Connected coverage for training, walking and behaviour guidance across the NCR.'),loc('10','ranchi','Ranchi','Jharkhand','Approachable, personalised pet care for a growing community of pet parents.'),loc('11','noida','Noida','Uttar Pradesh','Home and neighbourhood training that makes everyday routines easier to manage.')]

export const posts:BlogPost[]=[
 {id:'1',slug:'puppy-training-happy-well-behaved-companion',title:'Puppy Training: Build a Happy, Well-Behaved Companion',excerpt:'A practical guide to early routines, social confidence and the first skills your puppy needs.',category:'Puppy Training',date:'18 Aug 2026',readTime:'7 min',image:puppy,content:['Bringing home a puppy is exciting, but a thoughtful routine helps that excitement become a stable family life. Begin with predictable toilet breaks, meals, sleep and calm play.','Training should be short, clear and rewarding. Name response, recall, settling, gentle handling and appropriate chewing are more useful than chasing perfect obedience in the first weeks.','Socialisation is positive exposure, not uncontrolled contact. Help your puppy observe people, sounds, surfaces and suitable dogs at a pace that preserves confidence.']},
 {id:'2',slug:'basic-to-advanced-dog-training',title:'Basic to Advanced Dog Training: Build Discipline From Day One',excerpt:'Understand how reliable behaviour develops from simple foundations to real-world fluency.',category:'Dog Training',date:'10 Aug 2026',readTime:'8 min',image:dog,content:['Advanced work is only as strong as the foundations beneath it. Clear markers, useful rewards and consistent household rules create a language the dog can understand.','Distance, duration and distraction should be increased separately. When all three become difficult at once, performance often breaks down and frustration replaces learning.','A professional plan helps identify which level fits your dog now and how practice can progress safely.']},
 {id:'3',slug:'leash-training-practical-guide',title:'Leash Training for Dogs: A Practical Guide',excerpt:'Why dogs pull, how reinforcement shapes walking, and what makes calm leash skills last.',category:'Walking Skills',date:'02 Aug 2026',readTime:'6 min',image:dog,content:['Pulling works because it often moves the dog toward something valuable. Training changes the pattern by making proximity, check-ins and a loose lead equally meaningful.','Start where your dog can think. Reward a few connected steps, change direction smoothly and allow appropriate sniffing as part of the walk.','Equipment supports safety, but lasting improvement comes from technique, practice and an environment matched to the dog’s current ability.']},
 {id:'4',slug:'dog-behaviour-training-lasting-results',title:'Dog Behaviour Training for Lasting Results',excerpt:'A behaviour-led approach to barking, fear, anxiety, reactivity and household challenges.',category:'Behaviour',date:'25 Jul 2026',readTime:'7 min',image:dog,content:['Behaviour communicates a need, emotion or learned expectation. Effective change starts by identifying what happens before and after the behaviour.','Management prevents rehearsal while carefully planned training builds alternative responses. Medical contributors should be ruled out when behaviour changes suddenly or includes pain.','Complex behaviour deserves individual assessment; universal online advice cannot account for safety, history and context.']},
 {id:'5',slug:'cat-training-home-habits',title:'Cat Training for Better Home Habits',excerpt:'Use environment, choice and rewards to support litter, scratching and handling routines.',category:'Cat Training',date:'16 Jul 2026',readTime:'5 min',image:cat,content:['Cats learn continuously from their environment. Litter-box placement, substrate, cleanliness and access may matter as much as a training exercise.','Provide legal scratching options where the cat already chooses to scratch, then reward investigation and use.','Cooperative handling grows through brief, voluntary practice paired with something the cat values.']}]

export const testimonials:Testimonial[]=[{id:'t1',name:'Neha Bansal',location:'Noida, Delhi NCR',quote:'My dog had severe behavioural issues, and the behaviour-support program made a meaningful difference. The trainers were skilled, patient and kind.'},{id:'t2',name:'Rohit Sharma',location:'Sector 45, Gurugram',pet:'Labrador parent',quote:'I enrolled my Labrador in the advanced training package. The team was professional and the structured environment suited his energy and learning needs.'},{id:'t3',name:'Priya Mehra',location:'Dwarka, New Delhi',pet:'Puppy parent',quote:'The trainers were patient, knowledgeable and genuinely cared about my puppy’s development. I began seeing better routines within the first few sessions.'},{id:'t4',name:'Iqbal Dhingra',location:'Delhi NCR',pet:'Miniature Poodle parent',quote:'The trainer was gentle and an excellent teacher. My dog’s vocabulary and obedience improved substantially.'}]
export const faqs=[['What should a puppy learn first?','Begin with name response, toilet routines, handling, settling and simple cues such as sit and come. Short, rewarding sessions build confidence and make later obedience easier.'],['How do I choose the right dog-training package?','The right level depends on age, current skills, behaviour concerns and your goals. A consultation prevents paying for a package that is too basic or too advanced.'],['Do you use positive training methods?','Programs prioritise reward-based learning, clear communication and humane management. Plans are adapted to the individual pet without intimidation.'],['Can older dogs learn new behaviour?','Yes. Dogs can learn throughout life. Health, learning history and established habits may affect pace, so the plan should remain realistic and comfortable.'],['Can training take place at home?','Home sessions are available in active service areas and are useful for puppy routines, visitor manners and behaviours that happen in a specific environment.'],['How do I stop leash pulling?','Start in a low-distraction area, reward your dog for staying near you and progress gradually. Consistency matters because pulling becomes stronger whenever it successfully reaches a destination.'],['What is included in a standard groom?','A standard groom commonly includes bathing, brushing, drying, nail care, ear cleaning and appropriate hygiene trimming. Exact scope depends on coat and pet comfort.'],['Is it too late to train a cat?','No. Kittens and adult cats can learn litter routines, handling skills, recall, target behaviours and appropriate scratching choices through patient reinforcement.'],['How much does a dog walker cost?','Reference pricing varies by location, duration, frequency and walker experience. Pawrexio confirms current pricing for your locality instead of publishing an inaccurate universal rate.'],['Do pet parents participate?','Yes. Lasting improvement depends on daily routines, so every training plan includes clear pet-parent guidance and practice between sessions.']]
