import catalog from './catalog.json'
import cityContent from './location-content.json'
import type { BlogPost, Location, Program, Service, Testimonial } from './types'

export const siteSettings={strapline:'Smarter Pets. Happier You.',phone:'9211630927',alternatePhone:'',email:'Pets.heart2025@gmail.com',whatsapp:'9211630927',address:'Shop No. 6, TBS Road, near Krishna Chowk, Ashok Vihar Phase III Extension, Gurugram, Haryana 122001',socials:{facebook:'https://www.facebook.com/people/Pet-heart-fit/61578055757743/',instagram:'https://www.instagram.com/petheartfit?igsh=MTBhbmsxNnV4ZnBnZA==',youtube:'https://www.youtube.com/@petheartfitt',linkedin:''},footer:'Positive, personalised pet training and care that strengthens the bond between pets and their families.'}
const dog='/assets/real/obedience.webp',puppy='/assets/real/puppy-focus.webp',cat='/assets/real/cat-session.webp'
export const services:Service[]=[
 {id:'dog',slug:'dog-training',title:'Dog Training',kicker:'Professional training for everyday life',description:'Personalised dog training for puppies and adult dogs, from household manners and obedience to leash skills and complex behaviour support.',icon:'dog',duration:'Plan confirmed after consultation',suitable:'Puppies and adult dogs',benefits:['Clear everyday communication','Positive, practical routines','Pet-parent coaching'],includes:['Puppy and obedience foundations','Leash and recall skills','Behaviour-based programs'],content:['Effective dog training is about more than teaching commands. It helps your dog understand what is expected while giving you a reliable way to guide them at home and outdoors.','Every plan considers age, breed, learning history, home routine and the situations where behaviour becomes difficult. Skills are taught progressively and practised in the real environments where you need them.'],image:dog,category:'Dog Training'},
 {id:'cat',slug:'cat-training',title:'Cat Training',kicker:'Positive guidance for curious cats',description:'Feline-friendly training for litter habits, scratching, handling, routines and enrichment—without force or intimidation.',icon:'cat',duration:'Plan confirmed after consultation',suitable:'Kittens and adult cats',benefits:['Better home habits','Handling confidence','Healthy enrichment'],includes:['Litter and home routines','Target and recall foundations','Scratching and handling guidance'],content:['Cats learn through association, choice and rewards. A thoughtful plan can improve litter habits, reduce unwanted scratching and make everyday handling easier.','Sessions focus on the environment as much as the cat, helping pet parents provide suitable outlets for climbing, play, rest and natural behaviour.'],image:cat,category:'Cat Training'},
 {id:'groom',slug:'grooming',title:'Pet Grooming',kicker:'Comfort, hygiene and coat care',description:'Professional bathing, brushing, trimming and hygiene care for dogs and cats, with convenient at-home options where available.',icon:'scissors',duration:'Depends on coat and service',suitable:'Dogs and cats',benefits:['Coat and skin upkeep','Nail, ear and hygiene care','Low-stress handling'],includes:['Bathing and drying','Brushing and de-shedding','Nail and ear care'],content:['Regular grooming supports skin health, coat condition and comfort. It also creates an opportunity to notice changes that may need veterinary attention.','Service scope depends on coat, size, condition and handling needs. The final recommendation is confirmed before the appointment.'],image:puppy,category:'Grooming'},
 {id:'walk',slug:'dog-walking',title:'Dog Walking',kicker:'Healthy movement and calmer routines',description:'Reliable dog walking that supports physical activity, mental stimulation and better neighbourhood manners.',icon:'route',duration:'Duration selected at booking',suitable:'Dogs needing consistent exercise',benefits:['Appropriate daily activity','Mental stimulation','Calmer walking routines'],includes:['Individual walking plan','Basic leash reinforcement','Visit update'],content:['A good walk is more than exercise. Sniffing, exploring and calmly navigating the neighbourhood contribute to physical health and emotional wellbeing.','Walking plans consider age, fitness, weather, route safety and existing leash skills. Training support can be added when pulling or reactivity makes walks difficult.'],image:dog,category:'Dog Walking'},
 {id:'puppy',slug:'puppy-training',title:'Puppy Training',kicker:'Build the right habits early',description:'House routines, social confidence, bite inhibition and first cues for a happy, well-mannered companion.',icon:'sparkles',duration:'Details on consultation',suitable:'Young puppies and first-time pet parents',benefits:['Toilet and sleep routines','Early obedience','Safe socialisation'],image:puppy,category:'Dog Training'},
 {id:'leash',slug:'leash-training-for-dogs',title:'Leash Training for Dogs',kicker:'Better walks, better communication',description:'Practical loose-leash skills, check-ins and calmer responses around everyday distractions.',icon:'route',duration:'Details on consultation',suitable:'Dogs that pull or struggle on walks',benefits:['Reduced pulling','Safer handling','Improved focus'],image:dog,category:'Dog Training'},
 {id:'behaviour',slug:'canine-behaviour-training',title:'Canine Behaviour Training',kicker:'Understand the reason behind behaviour',description:'Assessment-led support for barking, fear, anxiety, reactivity, guarding and difficult household patterns.',icon:'brain',duration:'Assessment-led',suitable:'Dogs with behaviour concerns',benefits:['Trigger assessment','Management strategies','Progressive behaviour plan'],image:dog,category:'Dog Training'},
 {id:'walker',slug:'professional-dog-walker',title:'Professional Dog Walker',kicker:'Consistent care while you are busy',description:'Scheduled, responsible walks tailored to your dog’s energy, comfort and neighbourhood.',icon:'route',duration:'Selected at booking',suitable:'Adult dogs and suitable puppies',benefits:['Routine exercise','Supervised outdoor time','Visit updates'],image:dog,category:'Dog Walking'},
 {id:'bath',slug:'bath-and-brush',title:'Bath & Brush',kicker:'Everyday coat care',description:'A complete bath, coat and hygiene service for a clean, comfortable pet.',icon:'scissors',duration:'60–90 Minutes',suitable:'Cats & Dogs',price:'₹1,299',benefits:['Clean coat','Reduced loose hair','Comfort-focused handling'],includes:['Premium Shampoo Bath','Conditioner','Full Blow Dry','Complete Brushing','Nail Clipping','Ear Cleaning','Eye Cleaning','Paw Cleaning','Hygiene Cleaning','Pet-Friendly Fragrance'],blocks:[{kind:'heading',text:'Breed/Size Pricing'},{kind:'list',text:'Small: ₹1,299'},{kind:'list',text:'Medium: ₹1,499'},{kind:'list',text:'Large: ₹1,799'},{kind:'list',text:'XL / Heavy Coat: ₹1,999+'},{kind:'paragraph',text:'Additional charges may apply depending on breed, size and coat condition.'}],image:puppy,category:'Grooming'},
 {id:'tick',slug:'tick-treatment-bath-brush',title:'Tick Treatment With Bath & Brush',kicker:'Targeted coat and hygiene care',description:'Medicated tick and flea care combined with a complete bath and brush service.',icon:'scissors',duration:'90–120 Minutes',suitable:'Cats & Dogs',price:'₹1,799',benefits:['Targeted tick and flea care','Deep coat cleaning','Complete hygiene care'],includes:['Anti-Tick & Flea Treatment','Medicated Bath','Tick Removal','Premium Shampoo','Conditioner','Full Blow Dry','Deep Brushing','Nail Clipping','Ear Cleaning','Eye Cleaning','Paw Cleaning','Hygiene Cleaning','Pet-Friendly Fragrance'],blocks:[{kind:'heading',text:'Breed/Size Pricing'},{kind:'list',text:'Small: ₹1,799'},{kind:'list',text:'Medium: ₹1,999'},{kind:'list',text:'Large: ₹2,399'},{kind:'list',text:'XL / Heavy Coat: ₹2,799+'},{kind:'paragraph',text:'Additional charges may apply for severe tick/flea infestation or heavy coat conditions.'}],image:puppy,category:'Grooming'},
 {id:'haircut',slug:'haircut-and-styling',title:'Haircut & Styling',kicker:'Breed and coat-aware styling',description:'Complete bathing, coat preparation, haircut and styling tailored to your pet.',icon:'scissors',duration:'90–150 Minutes',suitable:'Cats & Dogs',price:'₹2,199',benefits:['Comfortable coat length','Face and body styling','Complete hygiene care'],includes:['Premium Bath','Conditioner','Full Blow Dry','Complete Brushing','Full Body Haircut','Face & Head Styling','Paw Trimming','Sanitary / Hygiene Trimming','Nail Clipping','Ear Cleaning','Eye Cleaning','Paw Cleaning','Pet-Friendly Fragrance'],blocks:[{kind:'heading',text:'Breed/Size Pricing'},{kind:'list',text:'Small: ₹2,199'},{kind:'list',text:'Medium: ₹2,499'},{kind:'list',text:'Large: ₹2,999'},{kind:'list',text:'XL / Heavy & Long Coat: ₹3,499+'},{kind:'paragraph',text:'Additional charges may apply for severe matting, extra-long coat or special grooming requirements.'}],image:puppy,category:'Grooming'},
 {id:'litter',slug:'litter-training-for-cat',title:'Litter Training for Cat',kicker:'Calmer, cleaner home routines',description:'Environmental and reward-based guidance for litter-box use and related household habits.',icon:'cat',duration:'Details on consultation',suitable:'Kittens and adult cats',benefits:['Appropriate setup','Habit support','Pet-parent guidance'],image:cat,category:'Cat Training'}]

const dogProgramOrder=['puppy-training','basic-training-for-dog','intermediate-dog-training','smart-training-for-dog','advanced-training-for-dog','master-training-for-dog','canine-behaviour-training','canine-behavior-therapy-cbt']
const catProgramOrder=['kitten-training','basic-cat-training','smart-cat-training']
const behaviourFeatures=['Excessive Barking','Jumping','Leash Pulling','Basic Obedience','Poor Listening','Unwanted Habits','Basic Socialisation','Impulse Control','Recall Training','Home Manners','Owner Guidance']
const therapyFeatures=['Aggression','Fear & Anxiety','Separation Problems','Excessive Barking','Leash Reactivity','Destructive Behaviour','Socialisation Problems','Hyperactivity','Impulse Control','Behaviour Modification','Owner Guidance','Regular Progress Check']
const catPrograms:Record<string,Partial<Program>>={
 'kitten-training':{title:'Kitten Training',duration:'1 Month',sessions:'12 Sessions | 1 Month',price:'₹8,999',regularPrice:'',includes:['Litter Training','Basic Commands','Behavior Correction','Scratching Management','Play & Socialization','Diet & Care Guidance']},
 'basic-cat-training':{title:'Basic Training',sessions:'24 Sessions',price:'₹17,999',regularPrice:'',includes:['Litter Training','Basic Commands','Behavior Correction','Scratching Management','Play & Socialization','Diet & Care Guidance','Problem Solving']},
 'smart-cat-training':{title:'Smart Training',sessions:'48 Sessions',price:'₹34,999',regularPrice:'',includes:['Advanced Commands','Behavior Modification','Litter & Hygiene Training','Scratching Management','Socialization & Confidence','Diet & Care Guidance','Problem Solving','Lifetime Support']}
}
function productionProgram(program:Program):Program{
 let next={...program}
 if(program.slug==='canine-behaviour-training')next={...next,title:'Canine Behaviour Training',duration:'4 Months',sessions:'48 Sessions | 4 Months',includes:behaviourFeatures,content:behaviourFeatures,blocks:behaviourFeatures.map(text=>({kind:'list',text}))}
 if(program.slug==='canine-behavior-therapy-cbt')next={...next,title:'Canine Behaviour Therapy Training (CBT)',duration:'6 Months',sessions:'72 Sessions | 6 Months',includes:therapyFeatures,content:therapyFeatures,blocks:therapyFeatures.map(text=>({kind:'list',text}))}
 if(catPrograms[program.slug]){next={...next,...catPrograms[program.slug]};next.content=next.includes;next.blocks=next.includes.map(text=>({kind:'list',text}))}
 return next
}
const bundledPrograms=(catalog as Program[]).filter(program=>program.category==='Dog Training'?dogProgramOrder.includes(program.slug):program.category==='Cat Training'?catProgramOrder.includes(program.slug):true).map(productionProgram)
export const programs:Program[]=[...dogProgramOrder.map(slug=>bundledPrograms.find(program=>program.slug===slug)).filter((program):program is Program=>Boolean(program)),...catProgramOrder.map(slug=>bundledPrograms.find(program=>program.slug===slug)).filter((program):program is Program=>Boolean(program)),...bundledPrograms.filter(program=>!['Dog Training','Cat Training'].includes(program.category))]
export const locations:Location[]=cityContent

export const posts:BlogPost[]=[
 {id:'1',slug:'puppy-training-happy-well-behaved-companion',title:'Puppy Training: Build a Happy, Well-Behaved Companion',excerpt:'A practical guide to early routines, social confidence and the first skills your puppy needs.',category:'Puppy Training',date:'18 Aug 2026',readTime:'7 min',image:puppy,content:['Bringing home a puppy is exciting, but a thoughtful routine helps that excitement become a stable family life. Begin with predictable toilet breaks, meals, sleep and calm play.','Training should be short, clear and rewarding. Name response, recall, settling, gentle handling and appropriate chewing are more useful than chasing perfect obedience in the first weeks.','Socialisation is positive exposure, not uncontrolled contact. Help your puppy observe people, sounds, surfaces and suitable dogs at a pace that preserves confidence.']},
 {id:'2',slug:'basic-to-advanced-dog-training',title:'Basic to Advanced Dog Training: Build Discipline From Day One',excerpt:'Understand how reliable behaviour develops from simple foundations to real-world fluency.',category:'Dog Training',date:'10 Aug 2026',readTime:'8 min',image:dog,content:['Advanced work is only as strong as the foundations beneath it. Clear markers, useful rewards and consistent household rules create a language the dog can understand.','Distance, duration and distraction should be increased separately. When all three become difficult at once, performance often breaks down and frustration replaces learning.','A professional plan helps identify which level fits your dog now and how practice can progress safely.']},
 {id:'3',slug:'leash-training-practical-guide',title:'Leash Training for Dogs: A Practical Guide',excerpt:'Why dogs pull, how reinforcement shapes walking, and what makes calm leash skills last.',category:'Walking Skills',date:'02 Aug 2026',readTime:'6 min',image:dog,content:['Pulling works because it often moves the dog toward something valuable. Training changes the pattern by making proximity, check-ins and a loose lead equally meaningful.','Start where your dog can think. Reward a few connected steps, change direction smoothly and allow appropriate sniffing as part of the walk.','Equipment supports safety, but lasting improvement comes from technique, practice and an environment matched to the dog’s current ability.']},
 {id:'4',slug:'dog-behaviour-training-lasting-results',title:'Dog Behaviour Training for Lasting Results',excerpt:'A behaviour-led approach to barking, fear, anxiety, reactivity and household challenges.',category:'Behaviour',date:'25 Jul 2026',readTime:'7 min',image:dog,content:['Behaviour communicates a need, emotion or learned expectation. Effective change starts by identifying what happens before and after the behaviour.','Management prevents rehearsal while carefully planned training builds alternative responses. Medical contributors should be ruled out when behaviour changes suddenly or includes pain.','Complex behaviour deserves individual assessment; universal online advice cannot account for safety, history and context.']},
 {id:'5',slug:'cat-training-home-habits',title:'Cat Training for Better Home Habits',excerpt:'Use environment, choice and rewards to support litter, scratching and handling routines.',category:'Cat Training',date:'16 Jul 2026',readTime:'5 min',image:cat,content:['Cats learn continuously from their environment. Litter-box placement, substrate, cleanliness and access may matter as much as a training exercise.','Provide legal scratching options where the cat already chooses to scratch, then reward investigation and use.','Cooperative handling grows through brief, voluntary practice paired with something the cat values.']},
 {id:'6',slug:'dog-training-in-mumbai-professional-trusted-services',title:'Dog Training in Mumbai: Professional & Trusted Pet Training Services',excerpt:'Practical training support for Mumbai pet parents, from puppy foundations and obedience to behaviour and leash skills.',category:'Dog Training',date:'10 Jul 2026',readTime:'7 min',image:'/assets/real/outdoor-focus.webp',content:['Life in Mumbai brings busy homes, lifts, traffic, visitors and stimulating walks. A useful training plan prepares dogs for those everyday situations instead of focusing only on commands in a quiet room.','Puppy training can establish toilet routines, calm handling, social confidence and early leash manners. Adult dogs may need structured obedience, recall practice, impulse control or individual support for barking, fear and reactivity.','Professional dog training should be adapted to your dog’s age, breed, health, history and home environment. Pawrexio uses positive, practical methods and gives pet parents clear exercises to continue between sessions.','For availability in your neighbourhood, explore our Mumbai service area or share your locality with the Pawrexio team.']},
 {id:'7',slug:'pet-training-happy-obedient-well-behaved-pets',title:'Pet Training for Happy, Obedient & Well-Behaved Pets',excerpt:'How personalised, reward-based pet training builds clearer communication, confidence and dependable everyday habits.',category:'Pet Training',date:'03 Jul 2026',readTime:'7 min',image:'/assets/real/training-session.webp',content:['Pet training is most effective when it improves daily life for both the animal and the family. Clear routines and consistent rewards help pets understand which choices work, while patient practice builds confidence.','A personalised plan can cover puppy foundations, dog obedience, leash training, cat home habits and behaviour concerns. The right starting point depends on age, temperament, learning history and the situations that are difficult now.','Short sessions are usually easier to repeat well. Practise one goal at a time, reward progress promptly and increase distraction only after the skill is understood.','Training is also pet-parent education. When everyone at home uses the same cues and boundaries, new habits become easier to maintain.']},
 {id:'8',slug:'puppy-obedience-classes-perfect-foundation',title:'Puppy Obedience Classes: Build the Perfect Foundation for Your Dog',excerpt:'Give your puppy an early foundation in household routines, communication, social confidence and essential cues.',category:'Puppy Training',date:'26 Jun 2026',readTime:'6 min',image:'/assets/real/puppy-sit.webp',content:['The first months are an important learning period, but good puppy training is not about rushing. Begin with predictable sleep, feeding and toilet routines, then add short lessons that keep the puppy engaged and successful.','Useful early skills include responding to their name, coming when called, settling, gentle handling, bite inhibition and walking comfortably on a leash. Sit and stay matter, but calm everyday behaviour matters just as much.','Socialisation means safe, positive exposure to people, sounds, surfaces, places and suitable animals. Let the puppy observe at a comfortable distance and avoid forcing interaction when they are worried.','Puppy obedience classes work best when pet parents practise the same reward-based techniques at home. Consistency turns a lesson into a reliable life skill.']}]

export const testimonials:Testimonial[]=[{id:'t1',name:'Neha Bansal',location:'Noida, Delhi NCR',quote:'My dog had severe behavioural issues, and the behaviour-support program made a meaningful difference. The trainers were skilled, patient and kind.'},{id:'t2',name:'Rohit Sharma',location:'Sector 45, Gurugram',pet:'Labrador parent',quote:'I enrolled my Labrador in the advanced training package. The team was professional and the structured environment suited his energy and learning needs.'},{id:'t3',name:'Priya Mehra',location:'Dwarka, New Delhi',pet:'Puppy parent',quote:'The trainers were patient, knowledgeable and genuinely cared about my puppy’s development. I began seeing better routines within the first few sessions.'},{id:'t4',name:'Iqbal Dhingra',location:'Delhi NCR',pet:'Miniature Poodle parent',quote:'The trainer was gentle and an excellent teacher. My dog’s vocabulary and obedience improved substantially.'},{id:'t5',name:'Mariyanus Beck',location:'Gurgaon',quote:'They trained my dog exceptionally well. The team was polite and professional, and my experience with them was really great.'},{id:'t6',name:'Rubina Ekka',location:'Noida',quote:'Excellent dog training service. The trainers were professional, patient and genuinely cared about my dog’s progress.'}]
export const faqs=[['What should a puppy learn first?','Begin with name response, toilet routines, handling, settling and simple cues such as sit and come. Short, rewarding sessions build confidence and make later obedience easier.'],['How do I choose the right dog-training package?','The right level depends on age, current skills, behaviour concerns and your goals. A consultation prevents paying for a package that is too basic or too advanced.'],['Do you use positive training methods?','Programs prioritise reward-based learning, clear communication and humane management. Plans are adapted to the individual pet without intimidation.'],['Can older dogs learn new behaviour?','Yes. Dogs can learn throughout life. Health, learning history and established habits may affect pace, so the plan should remain realistic and comfortable.'],['Can training take place at home?','Home sessions are available in active service areas and are useful for puppy routines, visitor manners and behaviours that happen in a specific environment.'],['How do I stop leash pulling?','Start in a low-distraction area, reward your dog for staying near you and progress gradually. Consistency matters because pulling becomes stronger whenever it successfully reaches a destination.'],['What is included in a standard groom?','A standard groom commonly includes bathing, brushing, drying, nail care, ear cleaning and appropriate hygiene trimming. Exact scope depends on coat and pet comfort.'],['Is it too late to train a cat?','No. Kittens and adult cats can learn litter routines, handling skills, recall, target behaviours and appropriate scratching choices through patient reinforcement.'],['How much does a dog walker cost?','Reference pricing varies by location, duration, frequency and walker experience. Pawrexio confirms current pricing for your locality instead of publishing an inaccurate universal rate.'],['Do pet parents participate?','Yes. Lasting improvement depends on daily routines, so every training plan includes clear pet-parent guidance and practice between sessions.']]
